import type { Building } from "./types";

export const BUILDINGS: Building[] = [
  {
    key: "granary",
    name: "Granary",
    era: "ancient",
    costGold: 50,
    costResources: [{ resourceKey: "timber", qty: 20 }],
    maintenance: 0,
    effects: { food: 5, populationCap: 3 },
    outputs: [{ resourceKey: "barley", perTick: 2 }],
    unlockTechKey: "agriculture",
  },
  {
    key: "farm",
    name: "Farm",
    era: "ancient",
    costGold: 40,
    costResources: [{ resourceKey: "timber", qty: 10 }, { resourceKey: "wood", qty: 10 }],
    maintenance: 0,
    effects: { food: 8 },
    outputs: [{ resourceKey: "wheat", perTick: 4 }],
    unlockTechKey: "agriculture",
  },
  {
    key: "ranch",
    name: "Ranch",
    era: "ancient",
    costGold: 40,
    costResources: [{ resourceKey: "timber", qty: 15 }],
    maintenance: 0,
    effects: { food: 4, gold: 1 },
    outputs: [
      { resourceKey: "cattle", perTick: 1 },
      { resourceKey: "milk", perTick: 2 },
      { resourceKey: "wool", perTick: 1 },
    ],
    unlockTechKey: "animal_husbandry",
  },
  {
    key: "quarry",
    name: "Quarry",
    era: "ancient",
    costGold: 60,
    costResources: [{ resourceKey: "timber", qty: 15 }],
    maintenance: 1,
    effects: { production: 4 },
    outputs: [{ resourceKey: "stone", perTick: 4 }, { resourceKey: "marble", perTick: 1 }],
    unlockTechKey: "mining",
  },
  {
    key: "mine",
    name: "Mine",
    era: "ancient",
    costGold: 80,
    costResources: [{ resourceKey: "timber", qty: 20 }],
    maintenance: 1,
    effects: { production: 6 },
    outputs: [
      { resourceKey: "iron-ore", perTick: 3 },
      { resourceKey: "coal", perTick: 2 },
      { resourceKey: "gold-ore", perTick: 1 },
    ],
    unlockTechKey: "mining",
  },
  {
    key: "workshop",
    name: "Workshop",
    era: "ancient",
    costGold: 90,
    costResources: [{ resourceKey: "timber", qty: 25 }],
    maintenance: 1,
    effects: { production: 7 },
    unlockTechKey: "wheel",
  },
  {
    key: "smithy",
    name: "Smithy",
    era: "ancient",
    costGold: 100,
    costResources: [{ resourceKey: "timber", qty: 20 }],
    maintenance: 1,
    effects: { production: 8 },
    unlockTechKey: "bronze_working",
  },
  {
    key: "library",
    name: "Library",
    era: "ancient",
    costGold: 90,
    costResources: [{ resourceKey: "timber", qty: 15 }],
    maintenance: 1,
    effects: { science: 3 },
    unlockTechKey: "writing",
  },
  {
    key: "monument",
    name: "Monument",
    era: "ancient",
    costGold: 60,
    costResources: [{ resourceKey: "stone", qty: 20 }],
    maintenance: 0,
    effects: { culture: 2, happiness: 3 },
    unlockTechKey: "masonry",
  },
  {
    key: "market",
    name: "Market",
    era: "classical",
    costGold: 120,
    costResources: [{ resourceKey: "timber", qty: 30 }],
    maintenance: 1,
    effects: { gold: 6 },
    unlockTechKey: "currency",
  },
  {
    key: "aqueduct",
    name: "Aqueduct",
    era: "classical",
    costGold: 150,
    costResources: [{ resourceKey: "stone", qty: 40 }],
    maintenance: 1,
    effects: { populationCap: 10, happiness: 3 },
    unlockTechKey: "construction",
  },
  {
    key: "walls",
    name: "City Walls",
    era: "classical",
    costGold: 130,
    costResources: [{ resourceKey: "stone", qty: 50 }],
    maintenance: 1,
    effects: { happiness: 2 },
    unlockTechKey: "construction",
  },
  {
    key: "academy",
    name: "Academy",
    era: "classical",
    costGold: 180,
    costResources: [{ resourceKey: "timber", qty: 25 }],
    maintenance: 2,
    effects: { science: 5 },
    unlockTechKey: "philosophy",
  },
  {
    key: "university",
    name: "University",
    era: "classical",
    costGold: 220,
    costResources: [{ resourceKey: "timber", qty: 40 }, { resourceKey: "stone", qty: 20 }],
    maintenance: 2,
    effects: { science: 8 },
    unlockTechKey: "mathematics",
  },
  {
    key: "theater",
    name: "Theater",
    era: "classical",
    costGold: 160,
    costResources: [{ resourceKey: "timber", qty: 30 }],
    maintenance: 2,
    effects: { culture: 6, happiness: 4 },
    unlockTechKey: "drama",
  },
  {
    key: "glassworks",
    name: "Glassworks",
    era: "classical",
    costGold: 140,
    costResources: [{ resourceKey: "clay", qty: 20 }, { resourceKey: "sand", qty: 20 }],
    maintenance: 1,
    effects: { gold: 4 },
    unlockTechKey: "glassblowing",
  },
  {
    key: "court",
    name: "Courthouse",
    era: "ancient",
    costGold: 110,
    costResources: [{ resourceKey: "timber", qty: 20 }, { resourceKey: "stone", qty: 20 }],
    maintenance: 1,
    effects: { happiness: 2 },
    unlockTechKey: "code_of_laws",
  },
  {
    key: "castle",
    name: "Castle",
    era: "medieval",
    costGold: 280,
    costResources: [{ resourceKey: "stone", qty: 80 }],
    maintenance: 2,
    effects: { happiness: 4 },
    unlockTechKey: "feudalism",
  },
  {
    key: "bank",
    name: "Bank",
    era: "medieval",
    costGold: 300,
    costResources: [{ resourceKey: "timber", qty: 40 }],
    maintenance: 2,
    effects: { gold: 10 },
    unlockTechKey: "medieval_finance",
  },
  {
    key: "harbor",
    name: "Harbor",
    era: "ancient",
    costGold: 130,
    costResources: [{ resourceKey: "timber", qty: 30 }],
    maintenance: 1,
    effects: { food: 4, gold: 4 },
    unlockTechKey: "sailing",
  },
  {
    key: "observatory",
    name: "Observatory",
    era: "renaissance",
    costGold: 300,
    costResources: [{ resourceKey: "timber", qty: 30 }, { resourceKey: "glass", qty: 10 }],
    maintenance: 2,
    effects: { science: 6 },
    unlockTechKey: "astronomy",
  },
  {
    key: "arsenal",
    name: "Arsenal",
    era: "renaissance",
    costGold: 320,
    costResources: [{ resourceKey: "iron", qty: 30 }, { resourceKey: "timber", qty: 30 }],
    maintenance: 3,
    effects: { production: 9 },
    unlockTechKey: "gunpowder",
  },
  {
    key: "laboratory",
    name: "Laboratory",
    era: "renaissance",
    costGold: 400,
    costResources: [{ resourceKey: "iron", qty: 20 }, { resourceKey: "glass", qty: 15 }],
    maintenance: 3,
    effects: { science: 10 },
    unlockTechKey: "chemistry",
  },
  {
    key: "refinery",
    name: "Refinery",
    era: "industrial",
    costGold: 600,
    costResources: [{ resourceKey: "iron", qty: 50 }, { resourceKey: "coal", qty: 30 }],
    maintenance: 4,
    effects: { production: 12 },
    unlockTechKey: "petroleum_refining",
  },
  {
    key: "power_plant",
    name: "Power Plant",
    era: "industrial",
    costGold: 800,
    costResources: [{ resourceKey: "iron", qty: 60 }, { resourceKey: "coal", qty: 40 }],
    maintenance: 5,
    effects: { production: 15 },
    unlockTechKey: "electricity",
  },
  {
    key: "foundry",
    name: "Foundry",
    era: "industrial",
    costGold: 500,
    costResources: [{ resourceKey: "iron", qty: 60 }, { resourceKey: "sand", qty: 20 }],
    maintenance: 3,
    effects: { production: 10 },
    unlockTechKey: "steam_power",
  },
  {
    key: "factory",
    name: "Factory",
    era: "industrial",
    costGold: 700,
    costResources: [{ resourceKey: "iron", qty: 50 }, { resourceKey: "coal", qty: 30 }],
    maintenance: 4,
    effects: { production: 18 },
    unlockTechKey: "electricity",
  },
  {
    key: "nanofab",
    name: "Nanofabricator",
    era: "information",
    costGold: 2000,
    costResources: [{ resourceKey: "silicon", qty: 50 }, { resourceKey: "rare-earth-elements", qty: 20 }],
    maintenance: 12,
    effects: { production: 40, science: 20 },
    unlockTechKey: "nanotechnology",
  },
];

export const BUILDING_BY_KEY: Map<string, Building> = new Map(BUILDINGS.map((b) => [b.key, b]));