import type { Recipe } from "./types";

export const RECIPES: Recipe[] = [
  {
    key: "smelting",
    name: "Smelting",
    outputKey: "copper",
    outputQty: 1,
    inputs: [{ resourceKey: "copper-ore", qty: 2 }],
    buildingKey: "smithy",
    unlockTechKey: "mining",
  },
  {
    key: "bronze_casting",
    name: "Bronze Casting",
    outputKey: "bronze",
    outputQty: 1,
    inputs: [{ resourceKey: "copper", qty: 2 }, { resourceKey: "tin", qty: 1 }],
    buildingKey: "smithy",
    unlockTechKey: "bronze_working",
  },
  {
    key: "iron_smelting",
    name: "Iron Smelting",
    outputKey: "iron",
    outputQty: 1,
    inputs: [{ resourceKey: "iron-ore", qty: 2 }, { resourceKey: "coal", qty: 1 }],
    buildingKey: "smithy",
    unlockTechKey: "iron_working",
  },
  {
    key: "steelmaking",
    name: "Steel Making",
    outputKey: "steel",
    outputQty: 1,
    inputs: [{ resourceKey: "iron", qty: 2 }, { resourceKey: "coal", qty: 1 }],
    buildingKey: "foundry",
    unlockTechKey: "steel_making",
  },
  {
    key: "electrolysis",
    name: "Aluminum Refining",
    outputKey: "aluminum",
    outputQty: 1,
    inputs: [{ resourceKey: "bauxite", qty: 2 }],
    buildingKey: "power_plant",
    unlockTechKey: "electricity",
  },
  {
    key: "milling",
    name: "Milling",
    outputKey: "flour",
    outputQty: 2,
    inputs: [{ resourceKey: "wheat", qty: 2 }],
    buildingKey: "granary",
    unlockTechKey: "agriculture",
  },
  {
    key: "baking",
    name: "Baking",
    outputKey: "bread",
    outputQty: 3,
    inputs: [{ resourceKey: "flour", qty: 2 }],
    buildingKey: "granary",
    unlockTechKey: "agriculture",
  },
  {
    key: "weaving",
    name: "Weaving",
    outputKey: "cloth",
    outputQty: 1,
    inputs: [{ resourceKey: "cotton", qty: 2 }, { resourceKey: "flax", qty: 1 }],
    buildingKey: "workshop",
    unlockTechKey: "guilds",
  },
  {
    key: "linenmaking",
    name: "Linen Making",
    outputKey: "linen",
    outputQty: 1,
    inputs: [{ resourceKey: "flax", qty: 2 }],
    buildingKey: "workshop",
    unlockTechKey: "guilds",
  },
  {
    key: "dyeing",
    name: "Dyeing",
    outputKey: "red-dye",
    outputQty: 1,
    inputs: [{ resourceKey: "cochineal", qty: 2 }],
    buildingKey: "workshop",
    unlockTechKey: null,
  },
  {
    key: "dyesynthesis",
    name: "Synthetic Dye Production",
    outputKey: "blue-dye",
    outputQty: 1,
    inputs: [{ resourceKey: "indigo", qty: 2 }, { resourceKey: "chemicals", qty: 1 }],
    buildingKey: "laboratory",
    unlockTechKey: "chemistry",
  },
  {
    key: "tannery",
    name: "Tannery",
    outputKey: "leather",
    outputQty: 1,
    inputs: [{ resourceKey: "cowhide", qty: 2 }],
    buildingKey: "workshop",
    unlockTechKey: "animal_husbandry",
  },
  {
    key: "dairy",
    name: "Dairy",
    outputKey: "cheese",
    outputQty: 2,
    inputs: [{ resourceKey: "milk", qty: 3 }],
    buildingKey: "farm",
    unlockTechKey: "animal_husbandry",
  },
  {
    key: "chocolatemaking",
    name: "Chocolate Making",
    outputKey: "chocolate",
    outputQty: 2,
    inputs: [{ resourceKey: "cocoa", qty: 2 }, { resourceKey: "sugar", qty: 1 }],
    buildingKey: "workshop",
    unlockTechKey: "preservation",
  },
  {
    key: "papermaking",
    name: "Papermaking",
    outputKey: "paper",
    outputQty: 1,
    inputs: [{ resourceKey: "pulp", qty: 2 }],
    buildingKey: "workshop",
    unlockTechKey: "writing",
  },
  {
    key: "cementmaking",
    name: "Cement Production",
    outputKey: "cement",
    outputQty: 1,
    inputs: [{ resourceKey: "limestone", qty: 2 }, { resourceKey: "clay", qty: 1 }],
    buildingKey: "quarry",
    unlockTechKey: "construction",
  },
  {
    key: "concretemaking",
    name: "Concrete Production",
    outputKey: "concrete",
    outputQty: 1,
    inputs: [{ resourceKey: "cement", qty: 1 }, { resourceKey: "gravel", qty: 1 }, { resourceKey: "sand", qty: 1 }],
    buildingKey: "quarry",
    unlockTechKey: "construction",
  },
  {
    key: "glassmaking",
    name: "Glassblowing",
    outputKey: "glass",
    outputQty: 1,
    inputs: [{ resourceKey: "sand", qty: 2 }],
    buildingKey: "glassworks",
    unlockTechKey: "glassblowing",
  },
  {
    key: "fertilizermaking",
    name: "Fertilizer Production",
    outputKey: "fertilizer",
    outputQty: 1,
    inputs: [{ resourceKey: "potash", qty: 1 }, { resourceKey: "phosphate-rock", qty: 1 }],
    buildingKey: "laboratory",
    unlockTechKey: "chemistry",
  },
  {
    key: "chemical_synthesis",
    name: "Chemical Synthesis",
    outputKey: "chemicals",
    outputQty: 1,
    inputs: [{ resourceKey: "sulfur", qty: 1 }, { resourceKey: "potash", qty: 1 }],
    buildingKey: "laboratory",
    unlockTechKey: "chemistry",
  },
  {
    key: "gunpowder_recipe",
    name: "Gunpowder Manufacture",
    outputKey: "explosives",
    outputQty: 2,
    inputs: [{ resourceKey: "sulfur", qty: 1 }, { resourceKey: "saltpeter", qty: 2 }, { resourceKey: "charcoal", qty: 1 }],
    buildingKey: "arsenal",
    unlockTechKey: "gunpowder",
  },
  {
    key: "refining_gasoline",
    name: "Refine Gasoline",
    outputKey: "gasoline",
    outputQty: 3,
    inputs: [{ resourceKey: "oil", qty: 2 }],
    buildingKey: "refinery",
    unlockTechKey: "petroleum_refining",
  },
  {
    key: "refining_diesel",
    name: "Refine Diesel",
    outputKey: "diesel",
    outputQty: 2,
    inputs: [{ resourceKey: "oil", qty: 2 }],
    buildingKey: "refinery",
    unlockTechKey: "petroleum_refining",
  },
  {
    key: "refining_kerosene",
    name: "Refine Kerosene",
    outputKey: "kerosene",
    outputQty: 2,
    inputs: [{ resourceKey: "oil", qty: 2 }],
    buildingKey: "refinery",
    unlockTechKey: "petroleum_refining",
  },
  {
    key: "refining_plastics",
    name: "Plastics",
    outputKey: "plastics",
    outputQty: 1,
    inputs: [{ resourceKey: "naphtha", qty: 2 }, { resourceKey: "chemicals", qty: 1 }],
    buildingKey: "refinery",
    unlockTechKey: "petroleum_refining",
  },
  {
    key: "refining_petrochemicals",
    name: "Petrochemicals",
    outputKey: "petrochemicals",
    outputQty: 2,
    inputs: [{ resourceKey: "oil", qty: 2 }],
    buildingKey: "refinery",
    unlockTechKey: "petroleum_refining",
  },
  {
    key: "semiconductormaking",
    name: "Semiconductor Fabrication",
    outputKey: "semiconductors",
    outputQty: 1,
    inputs: [{ resourceKey: "silicon", qty: 2 }],
    buildingKey: "laboratory",
    unlockTechKey: "semiconductors",
  },
  {
    key: "microchipmaking",
    name: "Microchip Fabrication",
    outputKey: "microchips",
    outputQty: 1,
    inputs: [{ resourceKey: "semiconductors", qty: 1 }, { resourceKey: "gold", qty: 1 }],
    buildingKey: "laboratory",
    unlockTechKey: "semiconductors",
  },
  {
    key: "batterymaking",
    name: "Battery Assembly",
    outputKey: "batteries",
    outputQty: 1,
    inputs: [{ resourceKey: "lithium", qty: 1 }, { resourceKey: "cobalt", qty: 1 }, { resourceKey: "graphite", qty: 1 }],
    buildingKey: "factory",
    unlockTechKey: "electricity",
  },
  {
    key: "enrichment",
    name: "Nuclear Enrichment",
    outputKey: "uranium",
    outputQty: 1,
    inputs: [{ resourceKey: "uranium-ore", qty: 3 }],
    buildingKey: "power_plant",
    unlockTechKey: "nuclear_fission",
  },
  {
    key: "nanofabrication",
    name: "Nanofabrication",
    outputKey: "graphene",
    outputQty: 1,
    inputs: [{ resourceKey: "carbon", qty: 2 }],
    buildingKey: "nanofab",
    unlockTechKey: "nanotechnology",
  },
  {
    key: "magnetmaking",
    name: "Superconductor Magnets",
    outputKey: "magnets",
    outputQty: 1,
    inputs: [{ resourceKey: "rare-earth-elements", qty: 2 }, { resourceKey: "superconductors", qty: 1 }],
    buildingKey: "nanofab",
    unlockTechKey: "superconductors",
  },
  {
    key: "fishing",
    name: "Fishing",
    outputKey: "fish",
    outputQty: 3,
    inputs: [],
    buildingKey: "harbor",
    unlockTechKey: "sailing",
  },
  {
    key: "minting",
    name: "Minting",
    outputKey: "gold",
    outputQty: 1,
    inputs: [{ resourceKey: "gold-ore", qty: 2 }],
    buildingKey: "smithy",
    unlockTechKey: "currency",
  },
];

export const RECIPE_BY_KEY: Map<string, Recipe> = new Map(RECIPES.map((r) => [r.key, r]));