import type { Technology } from "./types";

export const TECHNOLOGIES: Technology[] = [
  {
    key: "animal_husbandry",
    name: "Animal Husbandry",
    era: "ancient",
    cost: 25,
    description: "Domesticate animals for food and labor.",
    prerequisites: [],
    unlocksResources: ["cattle", "horses", "sheep", "goats", "pigs", "chickens", "wool", "milk"],
    unlocksBuildings: ["ranch"],
    unlocksUnits: ["cavalry_scout"],
    unlocksRecipes: ["tannery", "dairy"],
  },
  {
    key: "agriculture",
    name: "Agriculture",
    era: "ancient",
    cost: 25,
    description: "Tame the land. Grow staple crops.",
    prerequisites: [],
    unlocksResources: ["wheat", "barley", "rye", "oats", "millet", "sorghum", "flour", "flax"],
    unlocksBuildings: ["granary", "farm"],
    unlocksUnits: [],
    unlocksRecipes: ["milling"],
  },
  {
    key: "mining",
    name: "Mining",
    era: "ancient",
    cost: 25,
    description: "Extract stone and minerals from the earth.",
    prerequisites: [],
    unlocksResources: [
      "flint", "granite", "marble", "limestone", "sandstone", "slate", "basalt",
      "obsidian", "clay", "sand", "gravel", "salt", "gypsum", "quartz",
      "iron-ore", "hematite", "magnetite", "coal", "flint", "tin-ore", "copper-ore",
    ],
    unlocksBuildings: ["quarry", "mine"],
    unlocksUnits: [],
    unlocksRecipes: ["smelting"],
  },
  {
    key: "pottery",
    name: "Pottery",
    era: "ancient",
    cost: 30,
    description: "Fired clay containers — the first storehouses.",
    prerequisites: ["mining"],
    unlocksResources: ["clay"],
    unlocksBuildings: ["granary"],
    unlocksUnits: [],
    unlocksRecipes: [],
  },
  {
    key: "sailing",
    name: "Sailing",
    era: "ancient",
    cost: 30,
    description: "Cross the water; trade and fish the seas.",
    prerequisites: [],
    unlocksResources: ["fish", "fish-stocks", "salt"],
    unlocksBuildings: ["harbor"],
    unlocksUnits: ["galley"],
    unlocksRecipes: ["fishing"],
  },
  {
    key: "writing",
    name: "Writing",
    era: "ancient",
    cost: 50,
    description: "Record knowledge and pass it to the next generation.",
    prerequisites: ["pottery"],
    unlocksResources: ["papyrus", "parchment"],
    unlocksBuildings: ["library"],
    unlocksUnits: [],
    unlocksRecipes: ["papermaking"],
  },
  {
    key: "bronze_working",
    name: "Bronze Working",
    era: "ancient",
    cost: 60,
    description: "Alloy copper with tin to forge stronger tools.",
    prerequisites: ["mining"],
    unlocksResources: ["copper", "tin", "bronze"],
    unlocksBuildings: ["smithy"],
    unlocksUnits: ["warrior", "spearman"],
    unlocksRecipes: ["bronze_casting"],
  },
  {
    key: "iron_working",
    name: "Iron Working",
    era: "ancient",
    cost: 90,
    description: "Smelt iron ore into the metal that builds empires.",
    prerequisites: ["bronze_working"],
    unlocksResources: ["iron", "cast-iron"],
    unlocksBuildings: ["smithy"],
    unlocksUnits: ["swordsman"],
    unlocksRecipes: ["iron_smelting"],
  },
  {
    key: "wheel",
    name: "The Wheel",
    era: "ancient",
    cost: 60,
    description: "Revolutionize transport and production.",
    prerequisites: ["agriculture"],
    unlocksResources: [],
    unlocksBuildings: ["workshop"],
    unlocksUnits: ["chariot"],
    unlocksRecipes: [],
  },
  {
    key: "code_of_laws",
    name: "Code of Laws",
    era: "ancient",
    cost: 90,
    description: "Order the state with written law.",
    prerequisites: ["writing"],
    unlocksResources: [],
    unlocksBuildings: ["court"],
    unlocksUnits: [],
    unlocksRecipes: [],
  },
  {
    key: "currency",
    name: "Currency",
    era: "classical",
    cost: 120,
    description: "Coinage enables trade and treasuries.",
    prerequisites: ["code_of_laws"],
    unlocksResources: ["gold", "silver", "copper", "gold-ore", "silver-ore", "gold-ore"],
    unlocksBuildings: ["market"],
    unlocksUnits: [],
    unlocksRecipes: ["minting"],
  },
  {
    key: "construction",
    name: "Construction",
    era: "classical",
    cost: 120,
    description: "Master masonry and build on a grand scale.",
    prerequisites: ["masonry"],
    unlocksResources: ["cement", "concrete", "brick"],
    unlocksBuildings: ["aqueduct", "walls"],
    unlocksUnits: ["catapult"],
    unlocksRecipes: ["cementmaking", "concretemaking"],
  },
  {
    key: "masonry",
    name: "Masonry",
    era: "classical",
    cost: 90,
    description: "Quarry and shape stone into monuments.",
    prerequisites: ["mining"],
    unlocksResources: ["marble"],
    unlocksBuildings: ["monument"],
    unlocksUnits: [],
    unlocksRecipes: [],
  },
  {
    key: "philosophy",
    name: "Philosophy",
    era: "classical",
    cost: 150,
    description: "Question everything. Double your science.",
    prerequisites: ["writing"],
    unlocksResources: [],
    unlocksBuildings: ["academy"],
    unlocksUnits: [],
    unlocksRecipes: [],
  },
  {
    key: "mathematics",
    name: "Mathematics",
    era: "classical",
    cost: 130,
    description: "Numbers order the world.",
    prerequisites: ["construction"],
    unlocksResources: [],
    unlocksBuildings: ["university"],
    unlocksUnits: ["ballista"],
    unlocksRecipes: [],
  },
  {
    key: "engineering",
    name: "Engineering",
    era: "classical",
    cost: 160,
    description: "Build roads, bridges, and war engines.",
    prerequisites: ["mathematics"],
    unlocksResources: [],
    unlocksBuildings: [],
    unlocksUnits: ["catapult"],
    unlocksRecipes: [],
  },
  {
    key: "drama",
    name: "Drama & Poetry",
    era: "classical",
    cost: 100,
    description: "The arts shape a civilization's soul.",
    prerequisites: ["philosophy"],
    unlocksResources: ["gems"],
    unlocksBuildings: ["theater"],
    unlocksUnits: [],
    unlocksRecipes: [],
  },
  {
    key: "glassblowing",
    name: "Glassblowing",
    era: "classical",
    cost: 130,
    description: "Turn sand into wonder.",
    prerequisites: ["pottery"],
    unlocksResources: ["glass"],
    unlocksBuildings: ["glassworks"],
    unlocksUnits: [],
    unlocksRecipes: ["glassmaking"],
  },
  {
    key: "feudalism",
    name: "Feudalism",
    era: "medieval",
    cost: 200,
    description: "Bind land and loyalty.",
    prerequisites: ["code_of_laws"],
    unlocksResources: [],
    unlocksBuildings: ["castle"],
    unlocksUnits: ["knight", "pikeman"],
    unlocksRecipes: [],
  },
  {
    key: "medieval_finance",
    name: "Banking",
    era: "medieval",
    cost: 220,
    description: "Credit and interest oil the economy.",
    prerequisites: ["currency"],
    unlocksResources: [],
    unlocksBuildings: ["bank"],
    unlocksUnits: [],
    unlocksRecipes: [],
  },
  {
    key: "education",
    name: "Education",
    era: "medieval",
    cost: 250,
    description: "Schools multiply the learned.",
    prerequisites: ["philosophy"],
    unlocksResources: [],
    unlocksBuildings: ["university"],
    unlocksUnits: [],
    unlocksRecipes: [],
  },
  {
    key: "guilds",
    name: "Guilds",
    era: "medieval",
    cost: 240,
    description: "Artisans organize; goods improve.",
    prerequisites: ["medieval_finance"],
    unlocksResources: ["cloth", "linen"],
    unlocksBuildings: ["workshop"],
    unlocksUnits: [],
    unlocksRecipes: ["weaving", "dyeing"],
  },
  {
    key: "machinery",
    name: "Machinery",
    era: "medieval",
    cost: 300,
    description: "Cams, gears, and mills magnify labor.",
    prerequisites: ["engineering"],
    unlocksResources: ["machinery"],
    unlocksBuildings: [],
    unlocksUnits: [],
    unlocksRecipes: [],
  },
  {
    key: "gunpowder",
    name: "Gunpowder",
    era: "renaissance",
    cost: 320,
    description: "Fire and brimstone change warfare forever.",
    prerequisites: ["machinery"],
    unlocksResources: ["saltpeter", "explosives"],
    unlocksBuildings: ["arsenal"],
    unlocksUnits: ["musketman", "bombard", "cannon"],
    unlocksRecipes: ["gunpowder_recipe"],
  },
  {
    key: "printing_press",
    name: "Printing Press",
    era: "renaissance",
    cost: 300,
    description: "Knowledge printed in volume.",
    prerequisites: ["education"],
    unlocksResources: ["paper"],
    unlocksBuildings: [],
    unlocksUnits: [],
    unlocksRecipes: ["papermaking"],
  },
  {
    key: "navigation",
    name: "Navigation",
    era: "renaissance",
    cost: 350,
    description: "Sail beyond the horizon.",
    prerequisites: ["sailing"],
    unlocksResources: ["fish-stocks", "pearls"],
    unlocksBuildings: ["harbor"],
    unlocksUnits: ["caravel"],
    unlocksRecipes: [],
  },
  {
    key: "astronomy",
    name: "Astronomy",
    era: "renaissance",
    cost: 360,
    description: "Map the heavens to chart the seas.",
    prerequisites: ["navigation"],
    unlocksResources: [],
    unlocksBuildings: ["observatory"],
    unlocksUnits: [],
    unlocksRecipes: [],
  },
  {
    key: "metallurgy",
    name: "Metallurgy",
    era: "renaissance",
    cost: 400,
    description: "Alloys and tempering perfect metal.",
    prerequisites: ["iron_working"],
    unlocksResources: [],
    unlocksBuildings: [],
    unlocksUnits: [],
    unlocksRecipes: [],
  },
  {
    key: "chemistry",
    name: "Chemistry",
    era: "renaissance",
    cost: 420,
    description: "Mix the elements into new substances.",
    prerequisites: ["metallurgy"],
    unlocksResources: [
      "fertilizer", "chemicals", "pharmaceuticals", "synthetic-rubber",
      "nitrates", "phosphates", "ammonia", "red-dye", "blue-dye", "green-dye",
      "yellow-dye", "orange-dye", "purple-dye", "black-dye", "white-dye",
      "brown-dye", "pink-dye", "rubber",
    ],
    unlocksBuildings: ["laboratory", "factory"],
    unlocksUnits: [],
    unlocksRecipes: ["chemical_synthesis", "fertilizermaking", "dyesynthesis"],
  },
  {
    key: "steam_power",
    name: "Steam Power",
    era: "industrial",
    cost: 480,
    description: "Engine heat into motion.",
    prerequisites: ["machinery"],
    unlocksResources: [],
    unlocksBuildings: ["foundry", "power_plant"],
    unlocksUnits: ["ironclad"],
    unlocksRecipes: [],
  },
  {
    key: "steel_making",
    name: "Steel Making",
    era: "industrial",
    cost: 500,
    description: "The backbone of the industrial age.",
    prerequisites: ["steam_power"],
    unlocksResources: ["steel", "stainless-steel"],
    unlocksBuildings: ["foundry"],
    unlocksUnits: [],
    unlocksRecipes: ["steelmaking"],
  },
  {
    key: "electricity",
    name: "Electricity",
    era: "industrial",
    cost: 550,
    description: "Harness lightning to light the world.",
    prerequisites: ["steam_power"],
    unlocksResources: ["aluminum", "batteries", "solar-cells", "copper"],
    unlocksBuildings: ["power_plant", "factory"],
    unlocksUnits: [],
    unlocksRecipes: ["electrolysis", "batterymaking"],
  },
  {
    key: "petroleum_refining",
    name: "Petroleum Refining",
    era: "industrial",
    cost: 600,
    description: "Distill crude oil into modern fuels.",
    prerequisites: ["chemistry"],
    unlocksResources: [
      "oil", "natural-gas", "gasoline", "diesel", "kerosene", "jet-fuel",
      "fuel-oil", "lpg", "naphtha", "lubricants", "petrochemicals",
      "plastics", "plastic", "synthetic-fiber", "solvents", "asphalt",
    ],
    unlocksBuildings: ["refinery"],
    unlocksUnits: [],
    unlocksRecipes: ["refining_gasoline", "refining_diesel", "refining_kerosene", "refining_plastics", "refining_petrochemicals"],
  },
  {
    key: "electronics",
    name: "Electronics",
    era: "modern",
    cost: 700,
    description: "Vacuum tubes and circuits think for us.",
    prerequisites: ["electricity"],
    unlocksResources: ["electronics", "silicon", "gallium", "germanium", "fiber-optics"],
    unlocksBuildings: ["laboratory"],
    unlocksUnits: [],
    unlocksRecipes: [],
  },
  {
    key: "semiconductors",
    name: "Semiconductors",
    era: "modern",
    cost: 750,
    description: "Etch intelligence into crystal.",
    prerequisites: ["electronics"],
    unlocksResources: ["semiconductors", "microchips"],
    unlocksBuildings: [],
    unlocksUnits: [],
    unlocksRecipes: ["semiconductormaking", "microchipmaking"],
  },
  {
    key: "nuclear_fission",
    name: "Nuclear Fission",
    era: "modern",
    cost: 850,
    description: "Split the atom in two.",
    prerequisites: ["semiconductors"],
    unlocksResources: ["uranium", "thorium", "uranium-ore", "nuclear-energy"],
    unlocksBuildings: ["power_plant"],
    unlocksUnits: ["submarine"],
    unlocksRecipes: ["enrichment"],
  },
  {
    key: "rocketry",
    name: "Rocketry",
    era: "modern",
    cost: 900,
    description: "Reach beyond the sky.",
    prerequisites: ["electronics"],
    unlocksResources: ["space-ice", "lunar-regolith", "asteroid-metals", "platinum-group-metals"],
    unlocksBuildings: [],
    unlocksUnits: ["rocket"],
    unlocksRecipes: [],
  },
  {
    key: "nanotechnology",
    name: "Nanotechnology",
    era: "information",
    cost: 1200,
    description: "Build at the atomic scale.",
    prerequisites: ["semiconductors"],
    unlocksResources: [
      "graphene", "nanomaterials", "carbon-nanotubes", "quantum-materials",
      "superconductors", "smart-materials", "advanced-ceramics",
      "synthetic-diamonds",
    ],
    unlocksBuildings: ["nanofab"],
    unlocksUnits: [],
    unlocksRecipes: ["nanofabrication"],
  },
  {
    key: "superconductors",
    name: "Superconductors",
    era: "information",
    cost: 1300,
    description: "Current with zero resistance.",
    prerequisites: ["nanotechnology"],
    unlocksResources: ["magnets"],
    unlocksBuildings: [],
    unlocksUnits: [],
    unlocksRecipes: ["magnetmaking"],
  },
  {
    key: "nuclear_fusion",
    name: "Nuclear Fusion",
    era: "future",
    cost: 1600,
    description: "The power of the stars.",
    prerequisites: ["superconductors"],
    unlocksResources: ["deuterium", "tritium", "helium-3", "fusion-fuel"],
    unlocksBuildings: ["power_plant"],
    unlocksUnits: [],
    unlocksRecipes: [],
  },
  {
    key: "exotic_matter",
    name: "Exotic Matter",
    era: "future",
    cost: 2500,
    description: "Physics stretched past the known.",
    prerequisites: ["nuclear_fusion"],
    unlocksResources: ["exotic-matter", "antimatter"],
    unlocksBuildings: [],
    unlocksUnits: [],
    unlocksRecipes: [],
  },
  {
    key: "preservation",
    name: "Preservation",
    era: "medieval",
    cost: 180,
    description: "Keep food and precious goods from spoiling.",
    prerequisites: ["agriculture"],
    unlocksResources: ["chocolate"],
    unlocksBuildings: [],
    unlocksUnits: [],
    unlocksRecipes: ["chocolatemaking"],
  },
];

export const TECH_BY_KEY: Map<string, Technology> = new Map(TECHNOLOGIES.map((t) => [t.key, t]));

export function researchableTechs(researched: string[]): Technology[] {
  const known = new Set(researched);
  return TECHNOLOGIES.filter(
    (t) =>
      !known.has(t.key) &&
      (t.prerequisites.length === 0 || t.prerequisites.every((p) => known.has(p))),
  );
}

export const eraOrder: Record<string, number> = {
  ancient: 0,
  classical: 1,
  medieval: 2,
  renaissance: 3,
  industrial: 4,
  modern: 5,
  atomic: 6,
  information: 7,
  future: 8,
};