import type { Unit } from "./types";

export const UNITS: Unit[] = [
  {
    key: "scout",
    name: "Scout",
    kind: "military",
    era: "ancient",
    costGold: 30,
    costResources: [{ resourceKey: "wood", qty: 5 }],
    maintenance: 1,
    stats: { combat: 5, movement: 3, defense: 2 },
    unlockTechKey: null,
  },
  {
    key: "warrior",
    name: "Warrior",
    kind: "military",
    era: "ancient",
    costGold: 40,
    costResources: [],
    maintenance: 1,
    stats: { combat: 8, movement: 1, defense: 3 },
    unlockTechKey: "bronze_working",
  },
  {
    key: "spearman",
    name: "Spearman",
    kind: "military",
    era: "ancient",
    costGold: 45,
    costResources: [{ resourceKey: "wood", qty: 10 }],
    maintenance: 1,
    stats: { combat: 10, movement: 1, defense: 5 },
    unlockTechKey: "bronze_working",
  },
  {
    key: "swordsman",
    name: "Swordsman",
    kind: "military",
    era: "ancient",
    costGold: 60,
    costResources: [{ resourceKey: "iron", qty: 10 }],
    maintenance: 2,
    stats: { combat: 16, movement: 1, defense: 6 },
    unlockTechKey: "iron_working",
  },
  {
    key: "cavalry_scout",
    name: "Cavalry Scout",
    kind: "military",
    era: "ancient",
    costGold: 50,
    costResources: [{ resourceKey: "horses", qty: 10 }],
    maintenance: 2,
    stats: { combat: 12, movement: 3, defense: 4 },
    unlockTechKey: "animal_husbandry",
  },
  {
    key: "chariot",
    name: "War Chariot",
    kind: "military",
    era: "ancient",
    costGold: 70,
    costResources: [{ resourceKey: "horses", qty: 15 }, { resourceKey: "wood", qty: 20 }],
    maintenance: 2,
    stats: { combat: 14, movement: 4, defense: 4 },
    unlockTechKey: "wheel",
  },
  {
    key: "galley",
    name: "Galley",
    kind: "naval",
    era: "ancient",
    costGold: 60,
    costResources: [{ resourceKey: "wood", qty: 40 }],
    maintenance: 2,
    stats: { combat: 10, movement: 4, defense: 4 },
    unlockTechKey: "sailing",
  },
  {
    key: "ballista",
    name: "Ballista",
    kind: "siege",
    era: "classical",
    costGold: 90,
    costResources: [{ resourceKey: "wood", qty: 30 }],
    maintenance: 2,
    stats: { combat: 14, movement: 1, defense: 2 },
    unlockTechKey: "mathematics",
  },
  {
    key: "catapult",
    name: "Catapult",
    kind: "siege",
    era: "classical",
    costGold: 100,
    costResources: [{ resourceKey: "wood", qty: 40 }, { resourceKey: "stone", qty: 20 }],
    maintenance: 2,
    stats: { combat: 16, movement: 1, defense: 2 },
    unlockTechKey: "engineering",
  },
  {
    key: "knight",
    name: "Knight",
    kind: "military",
    era: "medieval",
    costGold: 160,
    costResources: [{ resourceKey: "horses", qty: 20 }, { resourceKey: "iron", qty: 20 }],
    maintenance: 4,
    stats: { combat: 24, movement: 3, defense: 8 },
    unlockTechKey: "feudalism",
  },
  {
    key: "pikeman",
    name: "Pikeman",
    kind: "military",
    era: "medieval",
    costGold: 120,
    costResources: [{ resourceKey: "iron", qty: 15 }, { resourceKey: "wood", qty: 20 }],
    maintenance: 3,
    stats: { combat: 20, movement: 1, defense: 10 },
    unlockTechKey: "feudalism",
  },
  {
    key: "crossbowman",
    name: "Crossbowman",
    kind: "military",
    era: "medieval",
    costGold: 130,
    costResources: [{ resourceKey: "wood", qty: 25 }],
    maintenance: 3,
    stats: { combat: 22, movement: 1, defense: 6 },
    unlockTechKey: "machinery",
  },
  {
    key: "musketman",
    name: "Musketman",
    kind: "military",
    era: "renaissance",
    costGold: 180,
    costResources: [{ resourceKey: "iron", qty: 20 }, { resourceKey: "saltpeter", qty: 10 }],
    maintenance: 4,
    stats: { combat: 28, movement: 1, defense: 8 },
    unlockTechKey: "gunpowder",
  },
  {
    key: "bombard",
    name: "Bombard",
    kind: "siege",
    era: "renaissance",
    costGold: 200,
    costResources: [{ resourceKey: "iron", qty: 30 }, { resourceKey: "saltpeter", qty: 10 }],
    maintenance: 4,
    stats: { combat: 26, movement: 1, defense: 4 },
    unlockTechKey: "gunpowder",
  },
  {
    key: "cannon",
    name: "Cannon",
    kind: "siege",
    era: "renaissance",
    costGold: 240,
    costResources: [{ resourceKey: "iron", qty: 40 }, { resourceKey: "saltpeter", qty: 15 }],
    maintenance: 5,
    stats: { combat: 30, movement: 1, defense: 4 },
    unlockTechKey: "gunpowder",
  },
  {
    key: "caravel",
    name: "Caravel",
    kind: "naval",
    era: "renaissance",
    costGold: 180,
    costResources: [{ resourceKey: "wood", qty: 60 }],
    maintenance: 4,
    stats: { combat: 20, movement: 5, defense: 6 },
    unlockTechKey: "navigation",
  },
  {
    key: "ironclad",
    name: "Ironclad",
    kind: "naval",
    era: "industrial",
    costGold: 400,
    costResources: [{ resourceKey: "iron", qty: 60 }, { resourceKey: "coal", qty: 40 }],
    maintenance: 8,
    stats: { combat: 40, movement: 3, defense: 16 },
    unlockTechKey: "steam_power",
  },
  {
    key: "rifleman",
    name: "Rifleman",
    kind: "military",
    era: "industrial",
    costGold: 260,
    costResources: [{ resourceKey: "iron", qty: 30 }, { resourceKey: "saltpeter", qty: 10 }],
    maintenance: 5,
    stats: { combat: 45, movement: 1, defense: 10 },
    unlockTechKey: "steel_making",
  },
  {
    key: "machine_gun",
    name: "Machine Gunner",
    kind: "military",
    era: "modern",
    costGold: 350,
    costResources: [{ resourceKey: "iron", qty: 40 }, { resourceKey: "petrochemicals", qty: 10 }],
    maintenance: 6,
    stats: { combat: 60, movement: 1, defense: 12 },
    unlockTechKey: "electronics",
  },
  {
    key: "submarine",
    name: "Submarine",
    kind: "naval",
    era: "modern",
    costGold: 600,
    costResources: [{ resourceKey: "steel", qty: 60 }, { resourceKey: "uranium", qty: 20 }],
    maintenance: 10,
    stats: { combat: 70, movement: 4, defense: 20 },
    unlockTechKey: "nuclear_fission",
  },
  {
    key: "rocket",
    name: "Rocket",
    kind: "naval",
    era: "modern",
    costGold: 800,
    costResources: [{ resourceKey: "steel", qty: 80 }, { resourceKey: "electronics", qty: 30 }],
    maintenance: 12,
    stats: { combat: 90, movement: 6, defense: 12 },
    unlockTechKey: "rocketry",
  },
];

export const UNIT_BY_KEY: Map<string, Unit> = new Map(UNITS.map((u) => [u.key, u]));