-- Auto-generated seed from src/lib/game. Do not edit by hand.
-- Regenerate with: bun scripts/generate-seed.mts

insert into public.resource_categories (key, name, color) values
  ('strategic', 'Strategic', '#f87171'),
  ('luxury', 'Luxury', '#fbbf24'),
  ('food', 'Food', '#4ade80'),
  ('agricultural', 'Agricultural', '#a3e635'),
  ('animal', 'Animal', '#fb923c'),
  ('mineral', 'Mineral', '#a8a29e'),
  ('metal', 'Metal', '#94a3b8'),
  ('precious', 'Precious Metal', '#fde047'),
  ('gemstone', 'Gemstone', '#c084fc'),
  ('energy', 'Energy', '#facc15'),
  ('chemical', 'Chemical', '#38bdf8'),
  ('forest', 'Forest', '#22c55e'),
  ('textile', 'Textile', '#e2e8f0'),
  ('marine', 'Marine', '#2dd4bf'),
  ('industrial', 'Industrial', '#fb7185'),
  ('technological', 'Technological', '#818cf8'),
  ('medicinal', 'Medicinal', '#34d399'),
  ('cultural', 'Cultural', '#f472b6') on conflict (key) do nothing;

insert into public.resources (key, name, category_key, tier, value, weight, unlock_tech_key) values
  ('rubber', 'Rubber', 'strategic', 2, 9, 0.8, 'chemistry'),
  ('ambergris', 'Ambergris', 'luxury', 2, 15, 0.8, null),
  ('beer', 'Beer', 'luxury', 2, 15, 0.8, null),
  ('caviar', 'Caviar', 'luxury', 2, 15, 0.8, null),
  ('chocolate', 'Chocolate', 'luxury', 2, 15, 0.8, 'preservation'),
  ('cider', 'Cider', 'luxury', 2, 15, 0.8, null),
  ('cocoa', 'Cocoa', 'luxury', 2, 15, 0.8, null),
  ('coffee', 'Coffee', 'luxury', 2, 15, 0.8, null),
  ('ebony', 'Ebony', 'luxury', 2, 15, 0.8, null),
  ('exotic-woods', 'Exotic Woods', 'luxury', 2, 15, 0.8, null),
  ('frankincense', 'Frankincense', 'luxury', 2, 15, 0.8, null),
  ('furs', 'Furs', 'luxury', 2, 15, 0.8, null),
  ('hops', 'Hops', 'luxury', 2, 15, 0.8, null),
  ('incense', 'Incense', 'luxury', 2, 15, 0.8, null),
  ('ivory', 'Ivory', 'luxury', 2, 15, 0.8, null),
  ('lacquer', 'Lacquer', 'luxury', 2, 15, 0.8, null),
  ('myrrh', 'Myrrh', 'luxury', 2, 15, 0.8, null),
  ('perfume', 'Perfume', 'luxury', 2, 15, 0.8, null),
  ('porcelain', 'Porcelain', 'luxury', 2, 15, 0.8, null),
  ('saffron', 'Saffron', 'luxury', 2, 15, 0.8, null),
  ('silk', 'Silk', 'luxury', 2, 15, 0.8, null),
  ('sugar', 'Sugar', 'luxury', 2, 15, 0.8, null),
  ('tea', 'Tea', 'luxury', 2, 15, 0.8, null),
  ('tobacco', 'Tobacco', 'luxury', 2, 15, 0.8, null),
  ('truffles', 'Truffles', 'luxury', 2, 15, 0.8, null),
  ('vanilla', 'Vanilla', 'luxury', 2, 15, 0.8, null),
  ('wine', 'Wine', 'luxury', 2, 15, 0.8, null),
  ('adzuki-beans', 'Adzuki Beans', 'food', 1, 1, 1, null),
  ('almonds', 'Almonds', 'food', 1, 1, 1, null),
  ('amaranth', 'Amaranth', 'food', 1, 1, 1, null),
  ('apple', 'Apple', 'food', 1, 1, 1, null),
  ('apricot', 'Apricot', 'food', 1, 1, 1, null),
  ('artichoke', 'Artichoke', 'food', 1, 1, 1, null),
  ('asparagus', 'Asparagus', 'food', 1, 1, 1, null),
  ('avocado', 'Avocado', 'food', 1, 1, 1, null),
  ('bamboo-shoots', 'Bamboo Shoots', 'food', 1, 1, 1, null),
  ('banana', 'Banana', 'food', 1, 1, 1, null),
  ('barley', 'Barley', 'food', 1, 1, 1, null),
  ('beet', 'Beet', 'food', 1, 1, 1, null),
  ('bell-pepper', 'Bell Pepper', 'food', 1, 1, 1, null),
  ('black-beans', 'Black Beans', 'food', 1, 1, 1, null),
  ('blackberry', 'Blackberry', 'food', 1, 1, 1, null),
  ('blueberry', 'Blueberry', 'food', 1, 1, 1, null),
  ('brazil-nuts', 'Brazil Nuts', 'food', 1, 1, 1, null),
  ('bread', 'Bread', 'food', 1, 1, 1, null),
  ('breadfruit', 'Breadfruit', 'food', 1, 1, 1, null),
  ('broccoli', 'Broccoli', 'food', 1, 1, 1, null),
  ('brussels-sprouts', 'Brussels Sprouts', 'food', 1, 1, 1, null),
  ('buckwheat', 'Buckwheat', 'food', 1, 1, 1, null),
  ('cabbage', 'Cabbage', 'food', 1, 1, 1, null),
  ('canola-oil', 'Canola Oil', 'food', 1, 1, 1, null),
  ('cantaloupe', 'Cantaloupe', 'food', 1, 1, 1, null),
  ('carrot', 'Carrot', 'food', 1, 1, 1, null),
  ('cashews', 'Cashews', 'food', 1, 1, 1, null),
  ('cassava', 'Cassava', 'food', 1, 1, 1, null),
  ('cauliflower', 'Cauliflower', 'food', 1, 1, 1, null),
  ('celery', 'Celery', 'food', 1, 1, 1, null),
  ('cherry', 'Cherry', 'food', 1, 1, 1, null),
  ('chestnuts', 'Chestnuts', 'food', 1, 1, 1, null),
  ('chia-seeds', 'Chia Seeds', 'food', 1, 1, 1, null),
  ('chickpeas', 'Chickpeas', 'food', 1, 1, 1, null),
  ('chili-pepper', 'Chili Pepper', 'food', 1, 1, 1, null),
  ('clementine', 'Clementine', 'food', 1, 1, 1, null),
  ('coconut', 'Coconut', 'food', 1, 1, 1, null),
  ('coconut-oil', 'Coconut Oil', 'food', 1, 1, 1, null),
  ('cranberry', 'Cranberry', 'food', 1, 1, 1, null),
  ('cucumber', 'Cucumber', 'food', 1, 1, 1, null),
  ('currant', 'Currant', 'food', 1, 1, 1, null),
  ('date', 'Date', 'food', 1, 1, 1, null),
  ('dragon-fruit', 'Dragon Fruit', 'food', 1, 1, 1, null),
  ('durian', 'Durian', 'food', 1, 1, 1, null),
  ('durum', 'Durum', 'food', 1, 1, 1, null),
  ('eggplant', 'Eggplant', 'food', 1, 1, 1, null),
  ('einkorn', 'Einkorn', 'food', 1, 1, 1, null),
  ('elderberry', 'Elderberry', 'food', 1, 1, 1, null),
  ('emmer', 'Emmer', 'food', 1, 1, 1, null),
  ('fava-beans', 'Fava Beans', 'food', 1, 1, 1, null),
  ('fig', 'Fig', 'food', 1, 1, 1, null),
  ('flaxseed', 'Flaxseed', 'food', 1, 1, 1, null),
  ('flour', 'Flour', 'food', 1, 1, 1, null),
  ('fonio', 'Fonio', 'food', 1, 1, 1, null),
  ('garlic', 'Garlic', 'food', 1, 1, 1, null),
  ('gooseberry', 'Gooseberry', 'food', 1, 1, 1, null),
  ('grape', 'Grape', 'food', 1, 1, 1, null),
  ('grapefruit', 'Grapefruit', 'food', 1, 1, 1, null),
  ('green-beans', 'Green Beans', 'food', 1, 1, 1, null),
  ('guava', 'Guava', 'food', 1, 1, 1, null),
  ('hazelnuts', 'Hazelnuts', 'food', 1, 1, 1, null),
  ('hemp-seeds', 'Hemp Seeds', 'food', 1, 1, 1, null),
  ('honey', 'Honey', 'food', 1, 1, 1, null),
  ('jackfruit', 'Jackfruit', 'food', 1, 1, 1, null),
  ('kale', 'Kale', 'food', 1, 1, 1, null),
  ('kidney-beans', 'Kidney Beans', 'food', 1, 1, 1, null),
  ('kiwi', 'Kiwi', 'food', 1, 1, 1, null),
  ('kumquat', 'Kumquat', 'food', 1, 1, 1, null),
  ('leek', 'Leek', 'food', 1, 1, 1, null),
  ('lemon', 'Lemon', 'food', 1, 1, 1, null),
  ('lentils', 'Lentils', 'food', 1, 1, 1, null),
  ('lettuce', 'Lettuce', 'food', 1, 1, 1, null),
  ('lime', 'Lime', 'food', 1, 1, 1, null),
  ('longan', 'Longan', 'food', 1, 1, 1, null),
  ('lupin', 'Lupin', 'food', 1, 1, 1, null),
  ('lychee', 'Lychee', 'food', 1, 1, 1, null),
  ('macadamia-nuts', 'Macadamia Nuts', 'food', 1, 1, 1, null),
  ('maize', 'Maize', 'food', 1, 1, 1, null),
  ('mandarin', 'Mandarin', 'food', 1, 1, 1, null),
  ('mango', 'Mango', 'food', 1, 1, 1, null),
  ('mangosteen', 'Mangosteen', 'food', 1, 1, 1, null),
  ('melon', 'Melon', 'food', 1, 1, 1, null),
  ('millet', 'Millet', 'food', 1, 1, 1, null),
  ('mulberry', 'Mulberry', 'food', 1, 1, 1, null),
  ('mung-beans', 'Mung Beans', 'food', 1, 1, 1, null),
  ('navy-beans', 'Navy Beans', 'food', 1, 1, 1, null),
  ('nectarine', 'Nectarine', 'food', 1, 1, 1, null),
  ('oats', 'Oats', 'food', 1, 1, 1, null),
  ('okra', 'Okra', 'food', 1, 1, 1, null),
  ('olive', 'Olive', 'food', 1, 1, 1, null),
  ('olive-oil', 'Olive Oil', 'food', 1, 1, 1, null),
  ('onion', 'Onion', 'food', 1, 1, 1, null),
  ('orange', 'Orange', 'food', 1, 1, 1, null),
  ('palm-oil', 'Palm Oil', 'food', 1, 1, 1, null),
  ('papaya', 'Papaya', 'food', 1, 1, 1, null),
  ('parsnip', 'Parsnip', 'food', 1, 1, 1, null),
  ('passion-fruit', 'Passion Fruit', 'food', 1, 1, 1, null),
  ('peach', 'Peach', 'food', 1, 1, 1, null),
  ('peanuts', 'Peanuts', 'food', 1, 1, 1, null),
  ('pear', 'Pear', 'food', 1, 1, 1, null),
  ('peas', 'Peas', 'food', 1, 1, 1, null),
  ('pecans', 'Pecans', 'food', 1, 1, 1, null),
  ('persimmon', 'Persimmon', 'food', 1, 1, 1, null),
  ('pine-nuts', 'Pine Nuts', 'food', 1, 1, 1, null),
  ('pineapple', 'Pineapple', 'food', 1, 1, 1, null),
  ('pinto-beans', 'Pinto Beans', 'food', 1, 1, 1, null),
  ('pistachios', 'Pistachios', 'food', 1, 1, 1, null),
  ('plum', 'Plum', 'food', 1, 1, 1, null),
  ('pomegranate', 'Pomegranate', 'food', 1, 1, 1, null),
  ('poppy-seeds', 'Poppy Seeds', 'food', 1, 1, 1, null),
  ('potato', 'Potato', 'food', 1, 1, 1, null),
  ('pumpkin', 'Pumpkin', 'food', 1, 1, 1, null),
  ('pumpkin-seeds', 'Pumpkin Seeds', 'food', 1, 1, 1, null),
  ('quince', 'Quince', 'food', 1, 1, 1, null),
  ('quinoa', 'Quinoa', 'food', 1, 1, 1, null),
  ('radish', 'Radish', 'food', 1, 1, 1, null),
  ('raspberry', 'Raspberry', 'food', 1, 1, 1, null),
  ('rice', 'Rice', 'food', 1, 1, 1, null),
  ('rutabaga', 'Rutabaga', 'food', 1, 1, 1, null),
  ('rye', 'Rye', 'food', 1, 1, 1, null),
  ('sesame', 'Sesame', 'food', 1, 1, 1, null),
  ('sesame-oil', 'Sesame Oil', 'food', 1, 1, 1, null),
  ('sorghum', 'Sorghum', 'food', 1, 1, 1, null),
  ('soursop', 'Soursop', 'food', 1, 1, 1, null),
  ('soy-oil', 'Soy Oil', 'food', 1, 1, 1, null),
  ('soybeans', 'Soybeans', 'food', 1, 1, 1, null),
  ('spelt', 'Spelt', 'food', 1, 1, 1, null),
  ('spinach', 'Spinach', 'food', 1, 1, 1, null),
  ('squash', 'Squash', 'food', 1, 1, 1, null),
  ('starfruit', 'Starfruit', 'food', 1, 1, 1, null),
  ('strawberry', 'Strawberry', 'food', 1, 1, 1, null),
  ('sunflower-oil', 'Sunflower Oil', 'food', 1, 1, 1, null),
  ('sunflower-seeds', 'Sunflower Seeds', 'food', 1, 1, 1, null),
  ('sweet-potato', 'Sweet Potato', 'food', 1, 1, 1, null),
  ('sweetcorn', 'Sweetcorn', 'food', 1, 1, 1, null),
  ('tamarind', 'Tamarind', 'food', 1, 1, 1, null),
  ('tangerine', 'Tangerine', 'food', 1, 1, 1, null),
  ('taro', 'Taro', 'food', 1, 1, 1, null),
  ('teff', 'Teff', 'food', 1, 1, 1, null),
  ('tomato', 'Tomato', 'food', 1, 1, 1, null),
  ('turnip', 'Turnip', 'food', 1, 1, 1, null),
  ('vinegar', 'Vinegar', 'food', 1, 1, 1, null),
  ('walnuts', 'Walnuts', 'food', 1, 1, 1, null),
  ('watermelon', 'Watermelon', 'food', 1, 1, 1, null),
  ('wheat', 'Wheat', 'food', 1, 1, 1, null),
  ('yam', 'Yam', 'food', 1, 1, 1, null),
  ('yeast', 'Yeast', 'food', 1, 1, 1, null),
  ('zucchini', 'Zucchini', 'food', 1, 1, 1, null),
  ('arable-land', 'Arable Land', 'agricultural', 1, 1, 1, null),
  ('fertile-soil', 'Fertile Soil', 'agricultural', 1, 1, 1, null),
  ('fresh-water', 'Fresh Water', 'agricultural', 1, 1, 1, null),
  ('palm', 'Palm', 'agricultural', 1, 1, 1, null),
  ('rapeseed', 'Rapeseed', 'agricultural', 1, 1, 1, null),
  ('sugar-beet', 'Sugar Beet', 'agricultural', 1, 1, 1, null),
  ('sugarcane', 'Sugarcane', 'agricultural', 1, 1, 1, null),
  ('sunflower', 'Sunflower', 'agricultural', 1, 1, 1, null),
  ('wetlands', 'Wetlands', 'agricultural', 1, 1, 1, null),
  ('alligator-leather', 'Alligator Leather', 'animal', 1, 1, 1, null),
  ('alpacas', 'Alpacas', 'animal', 1, 1, 1, null),
  ('animal-fat', 'Animal Fat', 'animal', 1, 1, 1, null),
  ('antler', 'Antler', 'animal', 1, 1, 1, null),
  ('beaver-fur', 'Beaver Fur', 'animal', 1, 1, 1, null),
  ('beef', 'Beef', 'animal', 1, 1, 1, null),
  ('bees', 'Bees', 'animal', 1, 1, 1, null),
  ('beeswax', 'Beeswax', 'animal', 1, 1, 1, null),
  ('bone', 'Bone', 'animal', 1, 1, 1, null),
  ('buffalo-hide', 'Buffalo Hide', 'animal', 1, 1, 1, null),
  ('butter', 'Butter', 'animal', 1, 1, 1, null),
  ('calfskin', 'Calfskin', 'animal', 1, 1, 1, null),
  ('camels', 'Camels', 'animal', 1, 1, 1, null),
  ('cattle', 'Cattle', 'animal', 1, 1, 1, null),
  ('cheese', 'Cheese', 'animal', 1, 1, 1, null),
  ('chicken', 'Chicken', 'animal', 1, 1, 1, null),
  ('chickens', 'Chickens', 'animal', 1, 1, 1, null),
  ('chinchilla-fur', 'Chinchilla Fur', 'animal', 1, 1, 1, null),
  ('cowhide', 'Cowhide', 'animal', 1, 1, 1, null),
  ('coyote-fur', 'Coyote Fur', 'animal', 1, 1, 1, null),
  ('crocodile-leather', 'Crocodile Leather', 'animal', 1, 1, 1, null),
  ('deer-hide', 'Deer Hide', 'animal', 1, 1, 1, null),
  ('donkeys', 'Donkeys', 'animal', 1, 1, 1, null),
  ('ducks', 'Ducks', 'animal', 1, 1, 1, null),
  ('eggs', 'Eggs', 'animal', 1, 1, 1, null),
  ('ermine-fur', 'Ermine Fur', 'animal', 1, 1, 1, null),
  ('fox-fur', 'Fox Fur', 'animal', 1, 1, 1, null),
  ('geese', 'Geese', 'animal', 1, 1, 1, null),
  ('goat-meat', 'Goat Meat', 'animal', 1, 1, 1, null),
  ('goats', 'Goats', 'animal', 1, 1, 1, null),
  ('goatskin', 'Goatskin', 'animal', 1, 1, 1, null),
  ('horn', 'Horn', 'animal', 1, 1, 1, null),
  ('horsehide', 'Horsehide', 'animal', 1, 1, 1, null),
  ('horses', 'Horses', 'animal', 1, 1, 1, null),
  ('leather', 'Leather', 'animal', 1, 1, 1, null),
  ('llamas', 'Llamas', 'animal', 1, 1, 1, null),
  ('lynx-fur', 'Lynx Fur', 'animal', 1, 1, 1, null),
  ('marten-fur', 'Marten Fur', 'animal', 1, 1, 1, null),
  ('milk', 'Milk', 'animal', 1, 1, 1, null),
  ('mink-fur', 'Mink Fur', 'animal', 1, 1, 1, null),
  ('mother-of-pearl', 'Mother of Pearl', 'animal', 1, 1, 1, null),
  ('mules', 'Mules', 'animal', 1, 1, 1, null),
  ('muskrat-fur', 'Muskrat Fur', 'animal', 1, 1, 1, null),
  ('mutton', 'Mutton', 'animal', 1, 1, 1, null),
  ('nutria-fur', 'Nutria Fur', 'animal', 1, 1, 1, null),
  ('ostrich-leather', 'Ostrich Leather', 'animal', 1, 1, 1, null),
  ('otter-fur', 'Otter Fur', 'animal', 1, 1, 1, null),
  ('pasture', 'Pasture', 'animal', 1, 1, 1, null),
  ('pigs', 'Pigs', 'animal', 1, 1, 1, null),
  ('pigskin', 'Pigskin', 'animal', 1, 1, 1, null),
  ('pork', 'Pork', 'animal', 1, 1, 1, null),
  ('rabbit-fur', 'Rabbit Fur', 'animal', 1, 1, 1, null),
  ('rabbits', 'Rabbits', 'animal', 1, 1, 1, null),
  ('raccoon-fur', 'Raccoon Fur', 'animal', 1, 1, 1, null),
  ('reindeer', 'Reindeer', 'animal', 1, 1, 1, null),
  ('reptile-leather', 'Reptile Leather', 'animal', 1, 1, 1, null),
  ('sable-fur', 'Sable Fur', 'animal', 1, 1, 1, null),
  ('seal-fur', 'Seal Fur', 'animal', 1, 1, 1, null),
  ('sheep', 'Sheep', 'animal', 1, 1, 1, null),
  ('sheepskin', 'Sheepskin', 'animal', 1, 1, 1, null),
  ('shell', 'Shell', 'animal', 1, 1, 1, null),
  ('snake-leather', 'Snake Leather', 'animal', 1, 1, 1, null),
  ('tortoiseshell', 'Tortoiseshell', 'animal', 1, 1, 1, null),
  ('turkeys', 'Turkeys', 'animal', 1, 1, 1, null),
  ('tusk', 'Tusk', 'animal', 1, 1, 1, null),
  ('water-buffalo', 'Water Buffalo', 'animal', 1, 1, 1, null),
  ('whale-bone', 'Whale Bone', 'animal', 1, 1, 1, null),
  ('wildlife', 'Wildlife', 'animal', 1, 1, 1, null),
  ('wolf-fur', 'Wolf Fur', 'animal', 1, 1, 1, null),
  ('wool', 'Wool', 'animal', 1, 1, 1, null),
  ('yaks', 'Yaks', 'animal', 1, 1, 1, null),
  ('apatite', 'Apatite', 'mineral', 1, 1, 1, null),
  ('asbestos', 'Asbestos', 'mineral', 1, 1, 1, null),
  ('barite', 'Barite', 'mineral', 1, 1, 1, null),
  ('basalt', 'Basalt', 'mineral', 1, 1, 1, 'mining'),
  ('bauxite', 'Bauxite', 'mineral', 1, 1, 1, null),
  ('bentonite', 'Bentonite', 'mineral', 1, 1, 1, null),
  ('borax', 'Borax', 'mineral', 1, 1, 1, null),
  ('calcite', 'Calcite', 'mineral', 1, 1, 1, null),
  ('cement', 'Cement', 'mineral', 1, 1, 1, 'construction'),
  ('chromium-ore', 'Chromium Ore', 'mineral', 1, 1, 1, null),
  ('cinnabar', 'Cinnabar', 'mineral', 1, 1, 1, null),
  ('clay', 'Clay', 'mineral', 1, 1, 1, 'mining'),
  ('cobalt-ore', 'Cobalt Ore', 'mineral', 1, 1, 1, null),
  ('copper-ore', 'Copper Ore', 'mineral', 1, 1, 1, null),
  ('diatomite', 'Diatomite', 'mineral', 1, 1, 1, null),
  ('dolomite', 'Dolomite', 'mineral', 1, 1, 1, null),
  ('feldspar', 'Feldspar', 'mineral', 1, 1, 1, null),
  ('flint', 'Flint', 'mineral', 1, 1, 1, 'mining'),
  ('fluorite', 'Fluorite', 'mineral', 1, 1, 1, null),
  ('galena', 'Galena', 'mineral', 1, 1, 1, null),
  ('gold-ore', 'Gold Ore', 'mineral', 1, 1, 1, null),
  ('granite', 'Granite', 'mineral', 1, 1, 1, 'mining'),
  ('graphite', 'Graphite', 'mineral', 1, 1, 1, null),
  ('gravel', 'Gravel', 'mineral', 1, 1, 1, 'mining'),
  ('gypsum', 'Gypsum', 'mineral', 1, 1, 1, 'mining'),
  ('hematite', 'Hematite', 'mineral', 1, 1, 1, 'mining'),
  ('ilmenite', 'Ilmenite', 'mineral', 1, 1, 1, null),
  ('iron-ore', 'Iron Ore', 'mineral', 1, 1, 1, 'mining'),
  ('kaolin', 'Kaolin', 'mineral', 1, 1, 1, null),
  ('lead-ore', 'Lead Ore', 'mineral', 1, 1, 1, null),
  ('limestone', 'Limestone', 'mineral', 1, 1, 1, 'mining'),
  ('lithium-ore', 'Lithium Ore', 'mineral', 1, 1, 1, null),
  ('magnetite', 'Magnetite', 'mineral', 1, 1, 1, 'mining'),
  ('malachite', 'Malachite', 'mineral', 1, 1, 1, null),
  ('manganese-ore', 'Manganese Ore', 'mineral', 1, 1, 1, null),
  ('marble', 'Marble', 'mineral', 1, 1, 1, 'mining'),
  ('mica', 'Mica', 'mineral', 1, 1, 1, null),
  ('monazite', 'Monazite', 'mineral', 1, 1, 1, null),
  ('nickel-ore', 'Nickel Ore', 'mineral', 1, 1, 1, null),
  ('obsidian', 'Obsidian', 'mineral', 1, 1, 1, 'mining'),
  ('perlite', 'Perlite', 'mineral', 1, 1, 1, null),
  ('phosphate-ore', 'Phosphate Ore', 'mineral', 1, 1, 1, null),
  ('phosphate-rock', 'Phosphate Rock', 'mineral', 1, 1, 1, null),
  ('platinum-ore', 'Platinum Ore', 'mineral', 1, 1, 1, null),
  ('potash', 'Potash', 'mineral', 1, 1, 1, null),
  ('potash-ore', 'Potash Ore', 'mineral', 1, 1, 1, null),
  ('pumice', 'Pumice', 'mineral', 1, 1, 1, null),
  ('pyrite', 'Pyrite', 'mineral', 1, 1, 1, null),
  ('quartz', 'Quartz', 'mineral', 1, 1, 1, 'mining'),
  ('rare-earth-ore', 'Rare Earth Ore', 'mineral', 1, 1, 1, 'electronics'),
  ('rutile', 'Rutile', 'mineral', 1, 1, 1, null),
  ('salt', 'Salt', 'mineral', 1, 1, 1, 'mining'),
  ('sand', 'Sand', 'mineral', 1, 1, 1, 'mining'),
  ('sandstone', 'Sandstone', 'mineral', 1, 1, 1, 'mining'),
  ('serpentine', 'Serpentine', 'mineral', 1, 1, 1, null),
  ('silver-ore', 'Silver Ore', 'mineral', 1, 1, 1, null),
  ('slate', 'Slate', 'mineral', 1, 1, 1, 'mining'),
  ('soapstone', 'Soapstone', 'mineral', 1, 1, 1, null),
  ('sphalerite', 'Sphalerite', 'mineral', 1, 1, 1, null),
  ('stone', 'Stone', 'mineral', 1, 1, 1, null),
  ('sulfur', 'Sulfur', 'mineral', 1, 1, 1, null),
  ('talc', 'Talc', 'mineral', 1, 1, 1, null),
  ('tin-ore', 'Tin Ore', 'mineral', 1, 1, 1, null),
  ('titanium-ore', 'Titanium Ore', 'mineral', 1, 1, 1, null),
  ('tungsten-ore', 'Tungsten Ore', 'mineral', 1, 1, 1, null),
  ('uranium-ore', 'Uranium Ore', 'mineral', 1, 1, 1, 'nuclear_fission'),
  ('vermiculite', 'Vermiculite', 'mineral', 1, 1, 1, null),
  ('zeolite', 'Zeolite', 'mineral', 1, 1, 1, null),
  ('zinc-ore', 'Zinc Ore', 'mineral', 1, 1, 1, null),
  ('aluminum', 'Aluminum', 'metal', 2, 6, 0.8, 'electricity'),
  ('antimony', 'Antimony', 'metal', 2, 6, 0.8, null),
  ('arsenic', 'Arsenic', 'metal', 2, 6, 0.8, null),
  ('bismuth', 'Bismuth', 'metal', 2, 6, 0.8, null),
  ('brass', 'Brass', 'metal', 2, 6, 0.8, 'bronze_working'),
  ('bronze', 'Bronze', 'metal', 2, 6, 0.8, 'bronze_working'),
  ('cadmium', 'Cadmium', 'metal', 2, 6, 0.8, null),
  ('calcium', 'Calcium', 'metal', 2, 6, 0.8, null),
  ('cast-iron', 'Cast Iron', 'metal', 2, 6, 0.8, 'iron_working'),
  ('chromium', 'Chromium', 'metal', 2, 6, 0.8, null),
  ('cobalt', 'Cobalt', 'metal', 2, 6, 0.8, null),
  ('columbium', 'Columbium', 'metal', 2, 6, 0.8, null),
  ('copper', 'Copper', 'metal', 2, 6, 0.8, null),
  ('electrum', 'Electrum', 'metal', 2, 6, 0.8, null),
  ('iron', 'Iron', 'metal', 2, 6, 0.8, 'iron_working'),
  ('lead', 'Lead', 'metal', 2, 6, 0.8, null),
  ('magnesium', 'Magnesium', 'metal', 2, 6, 0.8, null),
  ('manganese', 'Manganese', 'metal', 2, 6, 0.8, null),
  ('mercury', 'Mercury', 'metal', 2, 6, 0.8, null),
  ('nickel', 'Nickel', 'metal', 2, 6, 0.8, null),
  ('potassium', 'Potassium', 'metal', 2, 6, 0.8, null),
  ('silicon', 'Silicon', 'metal', 2, 6, 0.8, 'electronics'),
  ('sodium', 'Sodium', 'metal', 2, 6, 0.8, null),
  ('tin', 'Tin', 'metal', 2, 6, 0.8, null),
  ('titanium', 'Titanium', 'metal', 2, 6, 0.8, null),
  ('zinc', 'Zinc', 'metal', 2, 6, 0.8, null),
  ('gold', 'Gold', 'precious', 2, 24, 0.8, null),
  ('iridium', 'Iridium', 'precious', 2, 24, 0.8, null),
  ('osmium', 'Osmium', 'precious', 2, 24, 0.8, null),
  ('palladium', 'Palladium', 'precious', 2, 24, 0.8, null),
  ('platinum', 'Platinum', 'precious', 2, 24, 0.8, null),
  ('rhodium', 'Rhodium', 'precious', 2, 24, 0.8, null),
  ('ruthenium', 'Ruthenium', 'precious', 2, 24, 0.8, null),
  ('silver', 'Silver', 'precious', 2, 24, 0.8, null),
  ('agate', 'Agate', 'gemstone', 2, 30, 0.8, null),
  ('alexandrite', 'Alexandrite', 'gemstone', 2, 30, 0.8, null),
  ('amber', 'Amber', 'gemstone', 2, 30, 0.8, null),
  ('amethyst', 'Amethyst', 'gemstone', 2, 30, 0.8, null),
  ('aquamarine', 'Aquamarine', 'gemstone', 2, 30, 0.8, null),
  ('aventurine', 'Aventurine', 'gemstone', 2, 30, 0.8, null),
  ('benitoite', 'Benitoite', 'gemstone', 2, 30, 0.8, null),
  ('bloodstone', 'Bloodstone', 'gemstone', 2, 30, 0.8, null),
  ('carnelian', 'Carnelian', 'gemstone', 2, 30, 0.8, null),
  ('chrysoprase', 'Chrysoprase', 'gemstone', 2, 30, 0.8, null),
  ('citrine', 'Citrine', 'gemstone', 2, 30, 0.8, null),
  ('diamond', 'Diamond', 'gemstone', 2, 30, 0.8, null),
  ('emerald', 'Emerald', 'gemstone', 2, 30, 0.8, null),
  ('garnet', 'Garnet', 'gemstone', 2, 30, 0.8, null),
  ('gemstones', 'Gemstones', 'gemstone', 2, 30, 0.8, null),
  ('grandidierite', 'Grandidierite', 'gemstone', 2, 30, 0.8, null),
  ('jade', 'Jade', 'gemstone', 2, 30, 0.8, null),
  ('jasper', 'Jasper', 'gemstone', 2, 30, 0.8, null),
  ('jeremejevite', 'Jeremejevite', 'gemstone', 2, 30, 0.8, null),
  ('jet', 'Jet', 'gemstone', 2, 30, 0.8, null),
  ('labradorite', 'Labradorite', 'gemstone', 2, 30, 0.8, null),
  ('lapis-lazuli', 'Lapis Lazuli', 'gemstone', 2, 30, 0.8, null),
  ('moonstone', 'Moonstone', 'gemstone', 2, 30, 0.8, null),
  ('musgravite', 'Musgravite', 'gemstone', 2, 30, 0.8, null),
  ('onyx', 'Onyx', 'gemstone', 2, 30, 0.8, null),
  ('opal', 'Opal', 'gemstone', 2, 30, 0.8, null),
  ('painite', 'Painite', 'gemstone', 2, 30, 0.8, null),
  ('paraiba-tourmaline', 'Paraiba Tourmaline', 'gemstone', 2, 30, 0.8, null),
  ('peridot', 'Peridot', 'gemstone', 2, 30, 0.8, null),
  ('red-beryl', 'Red Beryl', 'gemstone', 2, 30, 0.8, null),
  ('ruby', 'Ruby', 'gemstone', 2, 30, 0.8, null),
  ('sapphire', 'Sapphire', 'gemstone', 2, 30, 0.8, null),
  ('spinel', 'Spinel', 'gemstone', 2, 30, 0.8, null),
  ('sunstone', 'Sunstone', 'gemstone', 2, 30, 0.8, null),
  ('taaffeite', 'Taaffeite', 'gemstone', 2, 30, 0.8, null),
  ('tanzanite', 'Tanzanite', 'gemstone', 2, 30, 0.8, null),
  ('topaz', 'Topaz', 'gemstone', 2, 30, 0.8, null),
  ('tourmaline', 'Tourmaline', 'gemstone', 2, 30, 0.8, null),
  ('turquoise', 'Turquoise', 'gemstone', 2, 30, 0.8, null),
  ('zircon', 'Zircon', 'gemstone', 2, 30, 0.8, null),
  ('biodiesel', 'Biodiesel', 'energy', 1, 2, 1, null),
  ('biogas', 'Biogas', 'energy', 1, 2, 1, null),
  ('biomass', 'Biomass', 'energy', 1, 2, 1, null),
  ('bitumen', 'Bitumen', 'energy', 1, 2, 1, null),
  ('charcoal', 'Charcoal', 'energy', 1, 2, 1, null),
  ('coal', 'Coal', 'energy', 1, 2, 1, 'mining'),
  ('deuterium', 'Deuterium', 'energy', 1, 2, 1, 'nuclear_fusion'),
  ('ethanol', 'Ethanol', 'energy', 1, 2, 1, null),
  ('fusion-fuel', 'Fusion Fuel', 'energy', 1, 2, 1, 'nuclear_fusion'),
  ('geothermal-energy', 'Geothermal Energy', 'energy', 1, 2, 1, null),
  ('helium-3', 'Helium-3', 'energy', 1, 2, 1, 'nuclear_fusion'),
  ('hydrogen', 'Hydrogen', 'energy', 1, 2, 1, null),
  ('hydropower', 'Hydropower', 'energy', 1, 2, 1, null),
  ('lignite', 'Lignite', 'energy', 1, 2, 1, null),
  ('methanol', 'Methanol', 'energy', 1, 2, 1, null),
  ('natural-gas', 'Natural Gas', 'energy', 1, 2, 1, null),
  ('nuclear-energy', 'Nuclear Energy', 'energy', 1, 2, 1, null),
  ('oil', 'Oil', 'energy', 1, 2, 1, null),
  ('oil-shale', 'Oil Shale', 'energy', 1, 2, 1, null),
  ('peat', 'Peat', 'energy', 1, 2, 1, null),
  ('saltpeter', 'Saltpeter', 'energy', 1, 2, 1, null),
  ('shale-oil', 'Shale Oil', 'energy', 1, 2, 1, null),
  ('solar-energy', 'Solar Energy', 'energy', 1, 2, 1, null),
  ('tar-sands', 'Tar Sands', 'energy', 1, 2, 1, null),
  ('thorium', 'Thorium', 'energy', 1, 2, 1, 'nuclear_fission'),
  ('tidal-energy', 'Tidal Energy', 'energy', 1, 2, 1, null),
  ('tritium', 'Tritium', 'energy', 1, 2, 1, 'nuclear_fusion'),
  ('uranium', 'Uranium', 'energy', 1, 2, 1, 'nuclear_fission'),
  ('wave-energy', 'Wave Energy', 'energy', 1, 2, 1, null),
  ('wind-energy', 'Wind Energy', 'energy', 1, 2, 1, null),
  ('wood-fuel', 'Wood Fuel', 'energy', 1, 2, 1, null),
  ('acetone', 'Acetone', 'chemical', 2, 9, 0.8, null),
  ('ammonia', 'Ammonia', 'chemical', 2, 9, 0.8, null),
  ('argon', 'Argon', 'chemical', 2, 9, 0.8, null),
  ('baking-soda', 'Baking Soda', 'chemical', 2, 9, 0.8, null),
  ('bromine', 'Bromine', 'chemical', 2, 9, 0.8, null),
  ('calcium-carbonate', 'Calcium Carbonate', 'chemical', 2, 9, 0.8, null),
  ('carbon', 'Carbon', 'chemical', 2, 9, 0.8, null),
  ('chlorine', 'Chlorine', 'chemical', 2, 9, 0.8, null),
  ('fluorine', 'Fluorine', 'chemical', 2, 9, 0.8, null),
  ('helium', 'Helium', 'chemical', 2, 9, 0.8, null),
  ('hydrochloric-acid', 'Hydrochloric Acid', 'chemical', 2, 9, 0.8, null),
  ('hydrogen-peroxide', 'Hydrogen Peroxide', 'chemical', 2, 9, 0.8, null),
  ('iodine', 'Iodine', 'chemical', 2, 9, 0.8, null),
  ('krypton', 'Krypton', 'chemical', 2, 9, 0.8, null),
  ('methane', 'Methane', 'chemical', 2, 9, 0.8, null),
  ('neon', 'Neon', 'chemical', 2, 9, 0.8, null),
  ('nitrates', 'Nitrates', 'chemical', 2, 9, 0.8, null),
  ('nitric-acid', 'Nitric Acid', 'chemical', 2, 9, 0.8, null),
  ('nitrogen', 'Nitrogen', 'chemical', 2, 9, 0.8, null),
  ('oxygen', 'Oxygen', 'chemical', 2, 9, 0.8, null),
  ('phosphates', 'Phosphates', 'chemical', 2, 9, 0.8, null),
  ('phosphorus', 'Phosphorus', 'chemical', 2, 9, 0.8, null),
  ('potassium-hydroxide', 'Potassium Hydroxide', 'chemical', 2, 9, 0.8, null),
  ('rock-salt', 'Rock Salt', 'chemical', 2, 9, 0.8, null),
  ('sea-salt', 'Sea Salt', 'chemical', 2, 9, 0.8, null),
  ('silicon-dioxide', 'Silicon Dioxide', 'chemical', 2, 9, 0.8, null),
  ('sodium-chloride', 'Sodium Chloride', 'chemical', 2, 9, 0.8, null),
  ('sodium-hydroxide', 'Sodium Hydroxide', 'chemical', 2, 9, 0.8, null),
  ('sulfur-dioxide', 'Sulfur Dioxide', 'chemical', 2, 9, 0.8, null),
  ('sulfuric-acid', 'Sulfuric Acid', 'chemical', 2, 9, 0.8, null),
  ('table-salt', 'Table Salt', 'chemical', 2, 9, 0.8, null),
  ('xenon', 'Xenon', 'chemical', 2, 9, 0.8, null),
  ('ash', 'Ash', 'forest', 1, 1, 1, null),
  ('bamboo', 'Bamboo', 'forest', 1, 1, 1, null),
  ('beech', 'Beech', 'forest', 1, 1, 1, null),
  ('birch', 'Birch', 'forest', 1, 1, 1, null),
  ('cedar', 'Cedar', 'forest', 1, 1, 1, null),
  ('cork', 'Cork', 'forest', 1, 1, 1, null),
  ('fine-wood', 'Fine Wood', 'forest', 1, 1, 1, null),
  ('fir', 'Fir', 'forest', 1, 1, 1, null),
  ('hardwood', 'Hardwood', 'forest', 1, 1, 1, null),
  ('mahogany', 'Mahogany', 'forest', 1, 1, 1, null),
  ('maple', 'Maple', 'forest', 1, 1, 1, null),
  ('oak', 'Oak', 'forest', 1, 1, 1, null),
  ('papyrus', 'Papyrus', 'forest', 1, 1, 1, null),
  ('pine', 'Pine', 'forest', 1, 1, 1, null),
  ('pulp', 'Pulp', 'forest', 1, 1, 1, null),
  ('resin', 'Resin', 'forest', 1, 1, 1, null),
  ('rosewood', 'Rosewood', 'forest', 1, 1, 1, null),
  ('rosewood-timber', 'Rosewood Timber', 'forest', 1, 1, 1, null),
  ('sap', 'Sap', 'forest', 1, 1, 1, null),
  ('softwood', 'Softwood', 'forest', 1, 1, 1, null),
  ('spruce', 'Spruce', 'forest', 1, 1, 1, null),
  ('teak', 'Teak', 'forest', 1, 1, 1, null),
  ('timber', 'Timber', 'forest', 1, 1, 1, null),
  ('walnut-wood', 'Walnut Wood', 'forest', 1, 1, 1, null),
  ('wood', 'Wood', 'forest', 1, 1, 1, null),
  ('wood-cherries', 'Wood Cherries', 'forest', 1, 1, 1, null),
  ('alpaca-fiber', 'Alpaca Fiber', 'textile', 1, 2, 1, null),
  ('angora', 'Angora', 'textile', 1, 2, 1, null),
  ('bamboo-fiber', 'Bamboo Fiber', 'textile', 1, 2, 1, null),
  ('brocatelle', 'Brocatelle', 'textile', 1, 2, 1, null),
  ('canvas', 'Canvas', 'textile', 1, 2, 1, null),
  ('cashmere', 'Cashmere', 'textile', 1, 2, 1, null),
  ('cloth', 'Cloth', 'textile', 1, 2, 1, null),
  ('coir', 'Coir', 'textile', 1, 2, 1, null),
  ('cotton', 'Cotton', 'textile', 1, 2, 1, null),
  ('damask', 'Damask', 'textile', 1, 2, 1, null),
  ('flax', 'Flax', 'textile', 1, 2, 1, null),
  ('hemp', 'Hemp', 'textile', 1, 2, 1, null),
  ('jute', 'Jute', 'textile', 1, 2, 1, null),
  ('kapok', 'Kapok', 'textile', 1, 2, 1, null),
  ('linen', 'Linen', 'textile', 1, 2, 1, null),
  ('linen-yarn', 'Linen Yarn', 'textile', 1, 2, 1, null),
  ('mohair', 'Mohair', 'textile', 1, 2, 1, null),
  ('ramie', 'Ramie', 'textile', 1, 2, 1, null),
  ('sisal', 'Sisal', 'textile', 1, 2, 1, null),
  ('tapestry', 'Tapestry', 'textile', 1, 2, 1, null),
  ('velvet', 'Velvet', 'textile', 1, 2, 1, null),
  ('anchovies', 'Anchovies', 'marine', 1, 1, 1, null),
  ('carp', 'Carp', 'marine', 1, 1, 1, null),
  ('clam', 'Clam', 'marine', 1, 1, 1, null),
  ('cod', 'Cod', 'marine', 1, 1, 1, null),
  ('coral', 'Coral', 'marine', 1, 1, 1, null),
  ('coral-reefs', 'Coral Reefs', 'marine', 1, 1, 1, null),
  ('crab', 'Crab', 'marine', 1, 1, 1, null),
  ('eel', 'Eel', 'marine', 1, 1, 1, null),
  ('fish', 'Fish', 'marine', 1, 1, 1, null),
  ('fish-oil', 'Fish Oil', 'marine', 1, 1, 1, null),
  ('fish-stocks', 'Fish Stocks', 'marine', 1, 1, 1, null),
  ('grouper', 'Grouper', 'marine', 1, 1, 1, null),
  ('haddock', 'Haddock', 'marine', 1, 1, 1, null),
  ('halibut', 'Halibut', 'marine', 1, 1, 1, null),
  ('herring', 'Herring', 'marine', 1, 1, 1, null),
  ('kelp', 'Kelp', 'marine', 1, 1, 1, null),
  ('lobster', 'Lobster', 'marine', 1, 1, 1, null),
  ('mackerel', 'Mackerel', 'marine', 1, 1, 1, null),
  ('marlin', 'Marlin', 'marine', 1, 1, 1, null),
  ('mussel', 'Mussel', 'marine', 1, 1, 1, null),
  ('octopus', 'Octopus', 'marine', 1, 1, 1, null),
  ('oyster', 'Oyster', 'marine', 1, 1, 1, null),
  ('pearls', 'Pearls', 'marine', 1, 1, 1, null),
  ('prawn', 'Prawn', 'marine', 1, 1, 1, null),
  ('salmon', 'Salmon', 'marine', 1, 1, 1, null),
  ('salt-spice', 'Salt Spice', 'marine', 1, 1, 1, null),
  ('sardines', 'Sardines', 'marine', 1, 1, 1, null),
  ('scallop', 'Scallop', 'marine', 1, 1, 1, null),
  ('sea-bass', 'Sea Bass', 'marine', 1, 1, 1, null),
  ('sea-urchin', 'Sea Urchin', 'marine', 1, 1, 1, null),
  ('seals', 'Seals', 'marine', 1, 1, 1, null),
  ('seaweed', 'Seaweed', 'marine', 1, 1, 1, null),
  ('shrimp', 'Shrimp', 'marine', 1, 1, 1, null),
  ('snail', 'Snail', 'marine', 1, 1, 1, null),
  ('snapper', 'Snapper', 'marine', 1, 1, 1, null),
  ('squid', 'Squid', 'marine', 1, 1, 1, null),
  ('swordfish', 'Swordfish', 'marine', 1, 1, 1, null),
  ('trout', 'Trout', 'marine', 1, 1, 1, null),
  ('tuna', 'Tuna', 'marine', 1, 1, 1, null),
  ('whales', 'Whales', 'marine', 1, 1, 1, null),
  ('armor-plate', 'Armor Plate', 'industrial', 3, 36, 0.5, null),
  ('asphalt', 'Asphalt', 'industrial', 3, 36, 0.5, null),
  ('brick', 'Brick', 'industrial', 3, 36, 0.5, null),
  ('carbon-fiber', 'Carbon Fiber', 'industrial', 3, 36, 0.5, null),
  ('ceramics', 'Ceramics', 'industrial', 3, 36, 0.5, null),
  ('chemicals', 'Chemicals', 'industrial', 3, 36, 0.5, 'chemistry'),
  ('concrete', 'Concrete', 'industrial', 3, 36, 0.5, 'construction'),
  ('diesel', 'Diesel', 'industrial', 3, 36, 0.5, 'petroleum_refining'),
  ('electronic-components', 'Electronic Components', 'industrial', 3, 36, 0.5, null),
  ('explosives', 'Explosives', 'industrial', 3, 36, 0.5, 'gunpowder'),
  ('fertilizer', 'Fertilizer', 'industrial', 3, 36, 0.5, 'chemistry'),
  ('fiberglass', 'Fiberglass', 'industrial', 3, 36, 0.5, null),
  ('fuel-oil', 'Fuel Oil', 'industrial', 3, 36, 0.5, 'petroleum_refining'),
  ('gasoline', 'Gasoline', 'industrial', 3, 36, 0.5, 'petroleum_refining'),
  ('glass', 'Glass', 'industrial', 3, 36, 0.5, 'glassblowing'),
  ('jet-fuel', 'Jet Fuel', 'industrial', 3, 36, 0.5, 'petroleum_refining'),
  ('kerosene', 'Kerosene', 'industrial', 3, 36, 0.5, 'petroleum_refining'),
  ('locomotive', 'Locomotive', 'industrial', 3, 36, 0.5, null),
  ('lpg', 'LPG', 'industrial', 3, 36, 0.5, 'petroleum_refining'),
  ('lubricants', 'Lubricants', 'industrial', 3, 36, 0.5, 'petroleum_refining'),
  ('machinery', 'Machinery', 'industrial', 3, 36, 0.5, null),
  ('naphtha', 'Naphtha', 'industrial', 3, 36, 0.5, 'petroleum_refining'),
  ('paper', 'Paper', 'industrial', 3, 36, 0.5, 'writing'),
  ('petrochemicals', 'Petrochemicals', 'industrial', 3, 36, 0.5, 'petroleum_refining'),
  ('pharmaceuticals', 'Pharmaceuticals', 'industrial', 3, 36, 0.5, 'chemistry'),
  ('plastic', 'Plastic', 'industrial', 3, 36, 0.5, 'petroleum_refining'),
  ('plastics', 'Plastics', 'industrial', 3, 36, 0.5, 'petroleum_refining'),
  ('semiconductor-materials', 'Semiconductor Materials', 'industrial', 3, 36, 0.5, null),
  ('solvents', 'Solvents', 'industrial', 3, 36, 0.5, 'petroleum_refining'),
  ('stainless-steel', 'Stainless Steel', 'industrial', 3, 36, 0.5, 'steel_making'),
  ('steel', 'Steel', 'industrial', 3, 36, 0.5, 'steel_making'),
  ('synthetic-fiber', 'Synthetic Fiber', 'industrial', 3, 36, 0.5, 'petroleum_refining'),
  ('synthetic-rubber', 'Synthetic Rubber', 'industrial', 3, 36, 0.5, 'petroleum_refining'),
  ('titanium-alloy', 'Titanium Alloy', 'industrial', 3, 36, 0.5, null),
  ('advanced-ceramics', 'Advanced Ceramics', 'technological', 4, 240, 0.25, 'nanotechnology'),
  ('antimatter', 'Antimatter', 'technological', 4, 240, 0.25, 'exotic_matter'),
  ('asteroid-metals', 'Asteroid Metals', 'technological', 4, 240, 0.25, 'rocketry'),
  ('batteries', 'Batteries', 'technological', 4, 240, 0.25, 'electricity'),
  ('beryllium', 'Beryllium', 'technological', 4, 240, 0.25, null),
  ('carbon-nanotubes', 'Carbon Nanotubes', 'technological', 4, 240, 0.25, 'nanotechnology'),
  ('cerium', 'Cerium', 'technological', 4, 240, 0.25, null),
  ('dysprosium', 'Dysprosium', 'technological', 4, 240, 0.25, null),
  ('electronics', 'Electronics', 'technological', 4, 240, 0.25, 'electronics'),
  ('erbium', 'Erbium', 'technological', 4, 240, 0.25, null),
  ('europium', 'Europium', 'technological', 4, 240, 0.25, null),
  ('exotic-matter', 'Exotic Matter', 'technological', 4, 240, 0.25, 'exotic_matter'),
  ('fiber-optics', 'Fiber Optics', 'technological', 4, 240, 0.25, 'electronics'),
  ('gadolinium', 'Gadolinium', 'technological', 4, 240, 0.25, null),
  ('gadolinium-alloy', 'Gadolinium Alloy', 'technological', 4, 240, 0.25, null),
  ('gallium', 'Gallium', 'technological', 4, 240, 0.25, 'electronics'),
  ('germanium', 'Germanium', 'technological', 4, 240, 0.25, 'electronics'),
  ('graphene', 'Graphene', 'technological', 4, 240, 0.25, 'nanotechnology'),
  ('hafnium', 'Hafnium', 'technological', 4, 240, 0.25, null),
  ('holmium', 'Holmium', 'technological', 4, 240, 0.25, null),
  ('indium', 'Indium', 'technological', 4, 240, 0.25, null),
  ('lanthanum', 'Lanthanum', 'technological', 4, 240, 0.25, null),
  ('lithium', 'Lithium', 'technological', 4, 240, 0.25, null),
  ('lunar-regolith', 'Lunar Regolith', 'technological', 4, 240, 0.25, 'rocketry'),
  ('lutetium', 'Lutetium', 'technological', 4, 240, 0.25, null),
  ('magnets', 'Magnets', 'technological', 4, 240, 0.25, 'superconductors'),
  ('microchips', 'Microchips', 'technological', 4, 240, 0.25, 'semiconductors'),
  ('molybdenum', 'Molybdenum', 'technological', 4, 240, 0.25, null),
  ('nanomaterials', 'Nanomaterials', 'technological', 4, 240, 0.25, 'nanotechnology'),
  ('neodymium', 'Neodymium', 'technological', 4, 240, 0.25, 'electronics'),
  ('niobium', 'Niobium', 'technological', 4, 240, 0.25, null),
  ('platinum-group-metals', 'Platinum Group Metals', 'technological', 4, 240, 0.25, 'rocketry'),
  ('praseodymium', 'Praseodymium', 'technological', 4, 240, 0.25, null),
  ('promethium', 'Promethium', 'technological', 4, 240, 0.25, null),
  ('quantum-materials', 'Quantum Materials', 'technological', 4, 240, 0.25, 'nanotechnology'),
  ('rare-earth-elements', 'Rare Earth Elements', 'technological', 4, 240, 0.25, 'electronics'),
  ('rhenium', 'Rhenium', 'technological', 4, 240, 0.25, null),
  ('samarium', 'Samarium', 'technological', 4, 240, 0.25, null),
  ('scandium', 'Scandium', 'technological', 4, 240, 0.25, null),
  ('semiconductors', 'Semiconductors', 'technological', 4, 240, 0.25, 'semiconductors'),
  ('smart-materials', 'Smart Materials', 'technological', 4, 240, 0.25, 'nanotechnology'),
  ('solar-cells', 'Solar Cells', 'technological', 4, 240, 0.25, 'electricity'),
  ('space-ice', 'Space Ice', 'technological', 4, 240, 0.25, 'rocketry'),
  ('superconductors', 'Superconductors', 'technological', 4, 240, 0.25, 'nanotechnology'),
  ('synthetic-diamonds', 'Synthetic Diamonds', 'technological', 4, 240, 0.25, 'nanotechnology'),
  ('tantalum', 'Tantalum', 'technological', 4, 240, 0.25, null),
  ('tellurium', 'Tellurium', 'technological', 4, 240, 0.25, null),
  ('terbium', 'Terbium', 'technological', 4, 240, 0.25, null),
  ('thulium', 'Thulium', 'technological', 4, 240, 0.25, null),
  ('tungsten', 'Tungsten', 'technological', 4, 240, 0.25, null),
  ('vanadium', 'Vanadium', 'technological', 4, 240, 0.25, null),
  ('ytterbium', 'Ytterbium', 'technological', 4, 240, 0.25, null),
  ('yttrium', 'Yttrium', 'technological', 4, 240, 0.25, null),
  ('zirconium', 'Zirconium', 'technological', 4, 240, 0.25, null),
  ('aloe-vera', 'Aloe Vera', 'medicinal', 1, 3, 1, null),
  ('belladonna', 'Belladonna', 'medicinal', 1, 3, 1, null),
  ('cannabis', 'Cannabis', 'medicinal', 1, 3, 1, null),
  ('chamomile', 'Chamomile', 'medicinal', 1, 3, 1, null),
  ('cinchona', 'Cinchona', 'medicinal', 1, 3, 1, null),
  ('eucalyptus', 'Eucalyptus', 'medicinal', 1, 3, 1, null),
  ('foxglove', 'Foxglove', 'medicinal', 1, 3, 1, null),
  ('ginseng', 'Ginseng', 'medicinal', 1, 3, 1, null),
  ('lavender', 'Lavender', 'medicinal', 1, 3, 1, null),
  ('licorice', 'Licorice', 'medicinal', 1, 3, 1, null),
  ('medicinal-herbs', 'Medicinal Herbs', 'medicinal', 1, 3, 1, null),
  ('opium-poppy', 'Opium Poppy', 'medicinal', 1, 3, 1, null),
  ('peppermint', 'Peppermint', 'medicinal', 1, 3, 1, null),
  ('tea-tree', 'Tea Tree', 'medicinal', 1, 3, 1, null),
  ('valerian', 'Valerian', 'medicinal', 1, 3, 1, null),
  ('willow-bark', 'Willow Bark', 'medicinal', 1, 3, 1, null),
  ('annatto', 'Annatto', 'cultural', 2, 15, 0.8, null),
  ('artworks', 'Artworks', 'cultural', 2, 15, 0.8, null),
  ('azurite', 'Azurite', 'cultural', 2, 15, 0.8, null),
  ('beetroot', 'Beetroot', 'cultural', 2, 15, 0.8, null),
  ('bergamot', 'Bergamot', 'cultural', 2, 15, 0.8, null),
  ('black-dye', 'Black Dye', 'cultural', 2, 15, 0.8, 'chemistry'),
  ('blue-dye', 'Blue Dye', 'cultural', 2, 15, 0.8, 'chemistry'),
  ('brazilwood', 'Brazilwood', 'cultural', 2, 15, 0.8, null),
  ('brown-dye', 'Brown Dye', 'cultural', 2, 15, 0.8, 'chemistry'),
  ('cedarwood', 'Cedarwood', 'cultural', 2, 15, 0.8, null),
  ('charcoal-black', 'Charcoal Black', 'cultural', 2, 15, 0.8, null),
  ('cochineal', 'Cochineal', 'cultural', 2, 15, 0.8, null),
  ('crystal', 'Crystal', 'cultural', 2, 15, 0.8, null),
  ('fine-ceramics', 'Fine Ceramics', 'cultural', 2, 15, 0.8, null),
  ('gems', 'Gems', 'cultural', 2, 15, 0.8, null),
  ('golden-idols', 'Golden Idols', 'cultural', 2, 15, 0.8, null),
  ('green-dye', 'Green Dye', 'cultural', 2, 15, 0.8, 'chemistry'),
  ('henna', 'Henna', 'cultural', 2, 15, 0.8, null),
  ('indigo', 'Indigo', 'cultural', 2, 15, 0.8, null),
  ('jasmine', 'Jasmine', 'cultural', 2, 15, 0.8, null),
  ('lac-dye', 'Lac Dye', 'cultural', 2, 15, 0.8, null),
  ('logwood', 'Logwood', 'cultural', 2, 15, 0.8, null),
  ('madder', 'Madder', 'cultural', 2, 15, 0.8, null),
  ('musical-instruments', 'Musical Instruments', 'cultural', 2, 15, 0.8, null),
  ('neroli', 'Neroli', 'cultural', 2, 15, 0.8, null),
  ('ochre', 'Ochre', 'cultural', 2, 15, 0.8, null),
  ('orange-dye', 'Orange Dye', 'cultural', 2, 15, 0.8, 'chemistry'),
  ('orpiment', 'Orpiment', 'cultural', 2, 15, 0.8, null),
  ('parchment', 'Parchment', 'cultural', 2, 15, 0.8, null),
  ('patchouli', 'Patchouli', 'cultural', 2, 15, 0.8, null),
  ('pink-dye', 'Pink Dye', 'cultural', 2, 15, 0.8, 'chemistry'),
  ('purple-dye', 'Purple Dye', 'cultural', 2, 15, 0.8, 'chemistry'),
  ('realgar', 'Realgar', 'cultural', 2, 15, 0.8, null),
  ('red-dye', 'Red Dye', 'cultural', 2, 15, 0.8, 'chemistry'),
  ('red-ochre', 'Red Ochre', 'cultural', 2, 15, 0.8, null),
  ('rose', 'Rose', 'cultural', 2, 15, 0.8, null),
  ('safflower', 'Safflower', 'cultural', 2, 15, 0.8, null),
  ('sandalwood', 'Sandalwood', 'cultural', 2, 15, 0.8, null),
  ('sepia', 'Sepia', 'cultural', 2, 15, 0.8, null),
  ('statuary', 'Statuary', 'cultural', 2, 15, 0.8, null),
  ('tyrian-purple', 'Tyrian Purple', 'cultural', 2, 15, 0.8, null),
  ('ultramarine', 'Ultramarine', 'cultural', 2, 15, 0.8, null),
  ('vetiver', 'Vetiver', 'cultural', 2, 15, 0.8, null),
  ('walnut', 'Walnut', 'cultural', 2, 15, 0.8, null),
  ('white-dye', 'White Dye', 'cultural', 2, 15, 0.8, 'chemistry'),
  ('woad', 'Woad', 'cultural', 2, 15, 0.8, null),
  ('yellow-dye', 'Yellow Dye', 'cultural', 2, 15, 0.8, 'chemistry'),
  ('yellow-ochre', 'Yellow Ochre', 'cultural', 2, 15, 0.8, null),
  ('ylang-ylang', 'Ylang-Ylang', 'cultural', 2, 15, 0.8, null) on conflict (key) do nothing;

insert into public.technologies (key, name, era, cost, description, prerequisites, unlocks_resources, unlocks_buildings, unlocks_units, unlocks_recipes) values
  ('animal_husbandry', 'Animal Husbandry', 'ancient', 25, 'Domesticate animals for food and labor.', ARRAY[]::text[], ARRAY['cattle', 'horses', 'sheep', 'goats', 'pigs', 'chickens', 'wool', 'milk']::text[], ARRAY['ranch']::text[], ARRAY['cavalry_scout']::text[], ARRAY['tannery', 'dairy']::text[]),
  ('agriculture', 'Agriculture', 'ancient', 25, 'Tame the land. Grow staple crops.', ARRAY[]::text[], ARRAY['wheat', 'barley', 'rye', 'oats', 'millet', 'sorghum', 'flour', 'flax']::text[], ARRAY['granary', 'farm']::text[], ARRAY[]::text[], ARRAY['milling']::text[]),
  ('mining', 'Mining', 'ancient', 25, 'Extract stone and minerals from the earth.', ARRAY[]::text[], ARRAY['flint', 'granite', 'marble', 'limestone', 'sandstone', 'slate', 'basalt', 'obsidian', 'clay', 'sand', 'gravel', 'salt', 'gypsum', 'quartz', 'iron-ore', 'hematite', 'magnetite', 'coal', 'flint', 'tin-ore', 'copper-ore']::text[], ARRAY['quarry', 'mine']::text[], ARRAY[]::text[], ARRAY['smelting']::text[]),
  ('pottery', 'Pottery', 'ancient', 30, 'Fired clay containers — the first storehouses.', ARRAY['mining']::text[], ARRAY['clay']::text[], ARRAY['granary']::text[], ARRAY[]::text[], ARRAY[]::text[]),
  ('sailing', 'Sailing', 'ancient', 30, 'Cross the water; trade and fish the seas.', ARRAY[]::text[], ARRAY['fish', 'fish-stocks', 'salt']::text[], ARRAY['harbor']::text[], ARRAY['galley']::text[], ARRAY['fishing']::text[]),
  ('writing', 'Writing', 'ancient', 50, 'Record knowledge and pass it to the next generation.', ARRAY['pottery']::text[], ARRAY['papyrus', 'parchment']::text[], ARRAY['library']::text[], ARRAY[]::text[], ARRAY['papermaking']::text[]),
  ('bronze_working', 'Bronze Working', 'ancient', 60, 'Alloy copper with tin to forge stronger tools.', ARRAY['mining']::text[], ARRAY['copper', 'tin', 'bronze']::text[], ARRAY['smithy']::text[], ARRAY['warrior', 'spearman']::text[], ARRAY['bronze_casting']::text[]),
  ('iron_working', 'Iron Working', 'ancient', 90, 'Smelt iron ore into the metal that builds empires.', ARRAY['bronze_working']::text[], ARRAY['iron', 'cast-iron']::text[], ARRAY['smithy']::text[], ARRAY['swordsman']::text[], ARRAY['iron_smelting']::text[]),
  ('wheel', 'The Wheel', 'ancient', 60, 'Revolutionize transport and production.', ARRAY['agriculture']::text[], ARRAY[]::text[], ARRAY['workshop']::text[], ARRAY['chariot']::text[], ARRAY[]::text[]),
  ('code_of_laws', 'Code of Laws', 'ancient', 90, 'Order the state with written law.', ARRAY['writing']::text[], ARRAY[]::text[], ARRAY['court']::text[], ARRAY[]::text[], ARRAY[]::text[]),
  ('currency', 'Currency', 'classical', 120, 'Coinage enables trade and treasuries.', ARRAY['code_of_laws']::text[], ARRAY['gold', 'silver', 'copper', 'gold-ore', 'silver-ore', 'gold-ore']::text[], ARRAY['market']::text[], ARRAY[]::text[], ARRAY['minting']::text[]),
  ('construction', 'Construction', 'classical', 120, 'Master masonry and build on a grand scale.', ARRAY['masonry']::text[], ARRAY['cement', 'concrete', 'brick']::text[], ARRAY['aqueduct', 'walls']::text[], ARRAY['catapult']::text[], ARRAY['cementmaking', 'concretemaking']::text[]),
  ('masonry', 'Masonry', 'classical', 90, 'Quarry and shape stone into monuments.', ARRAY['mining']::text[], ARRAY['marble']::text[], ARRAY['monument']::text[], ARRAY[]::text[], ARRAY[]::text[]),
  ('philosophy', 'Philosophy', 'classical', 150, 'Question everything. Double your science.', ARRAY['writing']::text[], ARRAY[]::text[], ARRAY['academy']::text[], ARRAY[]::text[], ARRAY[]::text[]),
  ('mathematics', 'Mathematics', 'classical', 130, 'Numbers order the world.', ARRAY['construction']::text[], ARRAY[]::text[], ARRAY['university']::text[], ARRAY['ballista']::text[], ARRAY[]::text[]),
  ('engineering', 'Engineering', 'classical', 160, 'Build roads, bridges, and war engines.', ARRAY['mathematics']::text[], ARRAY[]::text[], ARRAY[]::text[], ARRAY['catapult']::text[], ARRAY[]::text[]),
  ('drama', 'Drama & Poetry', 'classical', 100, 'The arts shape a civilization''s soul.', ARRAY['philosophy']::text[], ARRAY['gems']::text[], ARRAY['theater']::text[], ARRAY[]::text[], ARRAY[]::text[]),
  ('glassblowing', 'Glassblowing', 'classical', 130, 'Turn sand into wonder.', ARRAY['pottery']::text[], ARRAY['glass']::text[], ARRAY['glassworks']::text[], ARRAY[]::text[], ARRAY['glassmaking']::text[]),
  ('feudalism', 'Feudalism', 'medieval', 200, 'Bind land and loyalty.', ARRAY['code_of_laws']::text[], ARRAY[]::text[], ARRAY['castle']::text[], ARRAY['knight', 'pikeman']::text[], ARRAY[]::text[]),
  ('medieval_finance', 'Banking', 'medieval', 220, 'Credit and interest oil the economy.', ARRAY['currency']::text[], ARRAY[]::text[], ARRAY['bank']::text[], ARRAY[]::text[], ARRAY[]::text[]),
  ('education', 'Education', 'medieval', 250, 'Schools multiply the learned.', ARRAY['philosophy']::text[], ARRAY[]::text[], ARRAY['university']::text[], ARRAY[]::text[], ARRAY[]::text[]),
  ('guilds', 'Guilds', 'medieval', 240, 'Artisans organize; goods improve.', ARRAY['medieval_finance']::text[], ARRAY['cloth', 'linen']::text[], ARRAY['workshop']::text[], ARRAY[]::text[], ARRAY['weaving', 'dyeing']::text[]),
  ('machinery', 'Machinery', 'medieval', 300, 'Cams, gears, and mills magnify labor.', ARRAY['engineering']::text[], ARRAY['machinery']::text[], ARRAY[]::text[], ARRAY[]::text[], ARRAY[]::text[]),
  ('gunpowder', 'Gunpowder', 'renaissance', 320, 'Fire and brimstone change warfare forever.', ARRAY['machinery']::text[], ARRAY['saltpeter', 'explosives']::text[], ARRAY['arsenal']::text[], ARRAY['musketman', 'bombard', 'cannon']::text[], ARRAY['gunpowder_recipe']::text[]),
  ('printing_press', 'Printing Press', 'renaissance', 300, 'Knowledge printed in volume.', ARRAY['education']::text[], ARRAY['paper']::text[], ARRAY[]::text[], ARRAY[]::text[], ARRAY['papermaking']::text[]),
  ('navigation', 'Navigation', 'renaissance', 350, 'Sail beyond the horizon.', ARRAY['sailing']::text[], ARRAY['fish-stocks', 'pearls']::text[], ARRAY['harbor']::text[], ARRAY['caravel']::text[], ARRAY[]::text[]),
  ('astronomy', 'Astronomy', 'renaissance', 360, 'Map the heavens to chart the seas.', ARRAY['navigation']::text[], ARRAY[]::text[], ARRAY['observatory']::text[], ARRAY[]::text[], ARRAY[]::text[]),
  ('metallurgy', 'Metallurgy', 'renaissance', 400, 'Alloys and tempering perfect metal.', ARRAY['iron_working']::text[], ARRAY[]::text[], ARRAY[]::text[], ARRAY[]::text[], ARRAY[]::text[]),
  ('chemistry', 'Chemistry', 'renaissance', 420, 'Mix the elements into new substances.', ARRAY['metallurgy']::text[], ARRAY['fertilizer', 'chemicals', 'pharmaceuticals', 'synthetic-rubber', 'nitrates', 'phosphates', 'ammonia', 'red-dye', 'blue-dye', 'green-dye', 'yellow-dye', 'orange-dye', 'purple-dye', 'black-dye', 'white-dye', 'brown-dye', 'pink-dye', 'rubber']::text[], ARRAY['laboratory', 'factory']::text[], ARRAY[]::text[], ARRAY['chemical_synthesis', 'fertilizermaking', 'dyesynthesis']::text[]),
  ('steam_power', 'Steam Power', 'industrial', 480, 'Engine heat into motion.', ARRAY['machinery']::text[], ARRAY[]::text[], ARRAY['foundry', 'power_plant']::text[], ARRAY['ironclad']::text[], ARRAY[]::text[]),
  ('steel_making', 'Steel Making', 'industrial', 500, 'The backbone of the industrial age.', ARRAY['steam_power']::text[], ARRAY['steel', 'stainless-steel']::text[], ARRAY['foundry']::text[], ARRAY[]::text[], ARRAY['steelmaking']::text[]),
  ('electricity', 'Electricity', 'industrial', 550, 'Harness lightning to light the world.', ARRAY['steam_power']::text[], ARRAY['aluminum', 'batteries', 'solar-cells', 'copper']::text[], ARRAY['power_plant', 'factory']::text[], ARRAY[]::text[], ARRAY['electrolysis', 'batterymaking']::text[]),
  ('petroleum_refining', 'Petroleum Refining', 'industrial', 600, 'Distill crude oil into modern fuels.', ARRAY['chemistry']::text[], ARRAY['oil', 'natural-gas', 'gasoline', 'diesel', 'kerosene', 'jet-fuel', 'fuel-oil', 'lpg', 'naphtha', 'lubricants', 'petrochemicals', 'plastics', 'plastic', 'synthetic-fiber', 'solvents', 'asphalt']::text[], ARRAY['refinery']::text[], ARRAY[]::text[], ARRAY['refining_gasoline', 'refining_diesel', 'refining_kerosene', 'refining_plastics', 'refining_petrochemicals']::text[]),
  ('electronics', 'Electronics', 'modern', 700, 'Vacuum tubes and circuits think for us.', ARRAY['electricity']::text[], ARRAY['electronics', 'silicon', 'gallium', 'germanium', 'fiber-optics']::text[], ARRAY['laboratory']::text[], ARRAY[]::text[], ARRAY[]::text[]),
  ('semiconductors', 'Semiconductors', 'modern', 750, 'Etch intelligence into crystal.', ARRAY['electronics']::text[], ARRAY['semiconductors', 'microchips']::text[], ARRAY[]::text[], ARRAY[]::text[], ARRAY['semiconductormaking', 'microchipmaking']::text[]),
  ('nuclear_fission', 'Nuclear Fission', 'modern', 850, 'Split the atom in two.', ARRAY['semiconductors']::text[], ARRAY['uranium', 'thorium', 'uranium-ore', 'nuclear-energy']::text[], ARRAY['power_plant']::text[], ARRAY['submarine']::text[], ARRAY['enrichment']::text[]),
  ('rocketry', 'Rocketry', 'modern', 900, 'Reach beyond the sky.', ARRAY['electronics']::text[], ARRAY['space-ice', 'lunar-regolith', 'asteroid-metals', 'platinum-group-metals']::text[], ARRAY[]::text[], ARRAY['rocket']::text[], ARRAY[]::text[]),
  ('nanotechnology', 'Nanotechnology', 'information', 1200, 'Build at the atomic scale.', ARRAY['semiconductors']::text[], ARRAY['graphene', 'nanomaterials', 'carbon-nanotubes', 'quantum-materials', 'superconductors', 'smart-materials', 'advanced-ceramics', 'synthetic-diamonds']::text[], ARRAY['nanofab']::text[], ARRAY[]::text[], ARRAY['nanofabrication']::text[]),
  ('superconductors', 'Superconductors', 'information', 1300, 'Current with zero resistance.', ARRAY['nanotechnology']::text[], ARRAY['magnets']::text[], ARRAY[]::text[], ARRAY[]::text[], ARRAY['magnetmaking']::text[]),
  ('nuclear_fusion', 'Nuclear Fusion', 'future', 1600, 'The power of the stars.', ARRAY['superconductors']::text[], ARRAY['deuterium', 'tritium', 'helium-3', 'fusion-fuel']::text[], ARRAY['power_plant']::text[], ARRAY[]::text[], ARRAY[]::text[]),
  ('exotic_matter', 'Exotic Matter', 'future', 2500, 'Physics stretched past the known.', ARRAY['nuclear_fusion']::text[], ARRAY['exotic-matter', 'antimatter']::text[], ARRAY[]::text[], ARRAY[]::text[], ARRAY[]::text[]),
  ('preservation', 'Preservation', 'medieval', 180, 'Keep food and precious goods from spoiling.', ARRAY['agriculture']::text[], ARRAY['chocolate']::text[], ARRAY[]::text[], ARRAY[]::text[], ARRAY['chocolatemaking']::text[]) on conflict (key) do nothing;

insert into public.buildings (key, name, era, cost_gold, cost_resources, maintenance, effects, outputs, unlock_tech_key) values
  ('granary', 'Granary', 'ancient', 50, '[{"resourceKey":"timber","qty":20}]'::jsonb, 0, '{"food":5,"populationCap":3}'::jsonb, '[{"resourceKey":"barley","perTick":2}]'::jsonb, 'agriculture'),
  ('farm', 'Farm', 'ancient', 40, '[{"resourceKey":"timber","qty":10},{"resourceKey":"wood","qty":10}]'::jsonb, 0, '{"food":8}'::jsonb, '[{"resourceKey":"wheat","perTick":4}]'::jsonb, 'agriculture'),
  ('ranch', 'Ranch', 'ancient', 40, '[{"resourceKey":"timber","qty":15}]'::jsonb, 0, '{"food":4,"gold":1}'::jsonb, '[{"resourceKey":"cattle","perTick":1},{"resourceKey":"milk","perTick":2},{"resourceKey":"wool","perTick":1}]'::jsonb, 'animal_husbandry'),
  ('quarry', 'Quarry', 'ancient', 60, '[{"resourceKey":"timber","qty":15}]'::jsonb, 1, '{"production":4}'::jsonb, '[{"resourceKey":"stone","perTick":4},{"resourceKey":"marble","perTick":1}]'::jsonb, 'mining'),
  ('mine', 'Mine', 'ancient', 80, '[{"resourceKey":"timber","qty":20}]'::jsonb, 1, '{"production":6}'::jsonb, '[{"resourceKey":"iron-ore","perTick":3},{"resourceKey":"coal","perTick":2},{"resourceKey":"gold-ore","perTick":1}]'::jsonb, 'mining'),
  ('workshop', 'Workshop', 'ancient', 90, '[{"resourceKey":"timber","qty":25}]'::jsonb, 1, '{"production":7}'::jsonb, 'null'::jsonb, 'wheel'),
  ('smithy', 'Smithy', 'ancient', 100, '[{"resourceKey":"timber","qty":20}]'::jsonb, 1, '{"production":8}'::jsonb, 'null'::jsonb, 'bronze_working'),
  ('library', 'Library', 'ancient', 90, '[{"resourceKey":"timber","qty":15}]'::jsonb, 1, '{"science":3}'::jsonb, 'null'::jsonb, 'writing'),
  ('monument', 'Monument', 'ancient', 60, '[{"resourceKey":"stone","qty":20}]'::jsonb, 0, '{"culture":2,"happiness":3}'::jsonb, 'null'::jsonb, 'masonry'),
  ('market', 'Market', 'classical', 120, '[{"resourceKey":"timber","qty":30}]'::jsonb, 1, '{"gold":6}'::jsonb, 'null'::jsonb, 'currency'),
  ('aqueduct', 'Aqueduct', 'classical', 150, '[{"resourceKey":"stone","qty":40}]'::jsonb, 1, '{"populationCap":10,"happiness":3}'::jsonb, 'null'::jsonb, 'construction'),
  ('walls', 'City Walls', 'classical', 130, '[{"resourceKey":"stone","qty":50}]'::jsonb, 1, '{"happiness":2}'::jsonb, 'null'::jsonb, 'construction'),
  ('academy', 'Academy', 'classical', 180, '[{"resourceKey":"timber","qty":25}]'::jsonb, 2, '{"science":5}'::jsonb, 'null'::jsonb, 'philosophy'),
  ('university', 'University', 'classical', 220, '[{"resourceKey":"timber","qty":40},{"resourceKey":"stone","qty":20}]'::jsonb, 2, '{"science":8}'::jsonb, 'null'::jsonb, 'mathematics'),
  ('theater', 'Theater', 'classical', 160, '[{"resourceKey":"timber","qty":30}]'::jsonb, 2, '{"culture":6,"happiness":4}'::jsonb, 'null'::jsonb, 'drama'),
  ('glassworks', 'Glassworks', 'classical', 140, '[{"resourceKey":"clay","qty":20},{"resourceKey":"sand","qty":20}]'::jsonb, 1, '{"gold":4}'::jsonb, 'null'::jsonb, 'glassblowing'),
  ('court', 'Courthouse', 'ancient', 110, '[{"resourceKey":"timber","qty":20},{"resourceKey":"stone","qty":20}]'::jsonb, 1, '{"happiness":2}'::jsonb, 'null'::jsonb, 'code_of_laws'),
  ('castle', 'Castle', 'medieval', 280, '[{"resourceKey":"stone","qty":80}]'::jsonb, 2, '{"happiness":4}'::jsonb, 'null'::jsonb, 'feudalism'),
  ('bank', 'Bank', 'medieval', 300, '[{"resourceKey":"timber","qty":40}]'::jsonb, 2, '{"gold":10}'::jsonb, 'null'::jsonb, 'medieval_finance'),
  ('harbor', 'Harbor', 'ancient', 130, '[{"resourceKey":"timber","qty":30}]'::jsonb, 1, '{"food":4,"gold":4}'::jsonb, 'null'::jsonb, 'sailing'),
  ('observatory', 'Observatory', 'renaissance', 300, '[{"resourceKey":"timber","qty":30},{"resourceKey":"glass","qty":10}]'::jsonb, 2, '{"science":6}'::jsonb, 'null'::jsonb, 'astronomy'),
  ('arsenal', 'Arsenal', 'renaissance', 320, '[{"resourceKey":"iron","qty":30},{"resourceKey":"timber","qty":30}]'::jsonb, 3, '{"production":9}'::jsonb, 'null'::jsonb, 'gunpowder'),
  ('laboratory', 'Laboratory', 'renaissance', 400, '[{"resourceKey":"iron","qty":20},{"resourceKey":"glass","qty":15}]'::jsonb, 3, '{"science":10}'::jsonb, 'null'::jsonb, 'chemistry'),
  ('refinery', 'Refinery', 'industrial', 600, '[{"resourceKey":"iron","qty":50},{"resourceKey":"coal","qty":30}]'::jsonb, 4, '{"production":12}'::jsonb, 'null'::jsonb, 'petroleum_refining'),
  ('power_plant', 'Power Plant', 'industrial', 800, '[{"resourceKey":"iron","qty":60},{"resourceKey":"coal","qty":40}]'::jsonb, 5, '{"production":15}'::jsonb, 'null'::jsonb, 'electricity'),
  ('foundry', 'Foundry', 'industrial', 500, '[{"resourceKey":"iron","qty":60},{"resourceKey":"sand","qty":20}]'::jsonb, 3, '{"production":10}'::jsonb, 'null'::jsonb, 'steam_power'),
  ('factory', 'Factory', 'industrial', 700, '[{"resourceKey":"iron","qty":50},{"resourceKey":"coal","qty":30}]'::jsonb, 4, '{"production":18}'::jsonb, 'null'::jsonb, 'electricity'),
  ('nanofab', 'Nanofabricator', 'information', 2000, '[{"resourceKey":"silicon","qty":50},{"resourceKey":"rare-earth-elements","qty":20}]'::jsonb, 12, '{"production":40,"science":20}'::jsonb, 'null'::jsonb, 'nanotechnology') on conflict (key) do nothing;

insert into public.units (key, name, kind, era, cost_gold, cost_resources, maintenance, stats, unlock_tech_key) values
  ('scout', 'Scout', 'military', 'ancient', 30, '[{"resourceKey":"wood","qty":5}]'::jsonb, 1, '{"combat":5,"movement":3,"defense":2}'::jsonb, null),
  ('warrior', 'Warrior', 'military', 'ancient', 40, '[]'::jsonb, 1, '{"combat":8,"movement":1,"defense":3}'::jsonb, 'bronze_working'),
  ('spearman', 'Spearman', 'military', 'ancient', 45, '[{"resourceKey":"wood","qty":10}]'::jsonb, 1, '{"combat":10,"movement":1,"defense":5}'::jsonb, 'bronze_working'),
  ('swordsman', 'Swordsman', 'military', 'ancient', 60, '[{"resourceKey":"iron","qty":10}]'::jsonb, 2, '{"combat":16,"movement":1,"defense":6}'::jsonb, 'iron_working'),
  ('cavalry_scout', 'Cavalry Scout', 'military', 'ancient', 50, '[{"resourceKey":"horses","qty":10}]'::jsonb, 2, '{"combat":12,"movement":3,"defense":4}'::jsonb, 'animal_husbandry'),
  ('chariot', 'War Chariot', 'military', 'ancient', 70, '[{"resourceKey":"horses","qty":15},{"resourceKey":"wood","qty":20}]'::jsonb, 2, '{"combat":14,"movement":4,"defense":4}'::jsonb, 'wheel'),
  ('galley', 'Galley', 'naval', 'ancient', 60, '[{"resourceKey":"wood","qty":40}]'::jsonb, 2, '{"combat":10,"movement":4,"defense":4}'::jsonb, 'sailing'),
  ('ballista', 'Ballista', 'siege', 'classical', 90, '[{"resourceKey":"wood","qty":30}]'::jsonb, 2, '{"combat":14,"movement":1,"defense":2}'::jsonb, 'mathematics'),
  ('catapult', 'Catapult', 'siege', 'classical', 100, '[{"resourceKey":"wood","qty":40},{"resourceKey":"stone","qty":20}]'::jsonb, 2, '{"combat":16,"movement":1,"defense":2}'::jsonb, 'engineering'),
  ('knight', 'Knight', 'military', 'medieval', 160, '[{"resourceKey":"horses","qty":20},{"resourceKey":"iron","qty":20}]'::jsonb, 4, '{"combat":24,"movement":3,"defense":8}'::jsonb, 'feudalism'),
  ('pikeman', 'Pikeman', 'military', 'medieval', 120, '[{"resourceKey":"iron","qty":15},{"resourceKey":"wood","qty":20}]'::jsonb, 3, '{"combat":20,"movement":1,"defense":10}'::jsonb, 'feudalism'),
  ('crossbowman', 'Crossbowman', 'military', 'medieval', 130, '[{"resourceKey":"wood","qty":25}]'::jsonb, 3, '{"combat":22,"movement":1,"defense":6}'::jsonb, 'machinery'),
  ('musketman', 'Musketman', 'military', 'renaissance', 180, '[{"resourceKey":"iron","qty":20},{"resourceKey":"saltpeter","qty":10}]'::jsonb, 4, '{"combat":28,"movement":1,"defense":8}'::jsonb, 'gunpowder'),
  ('bombard', 'Bombard', 'siege', 'renaissance', 200, '[{"resourceKey":"iron","qty":30},{"resourceKey":"saltpeter","qty":10}]'::jsonb, 4, '{"combat":26,"movement":1,"defense":4}'::jsonb, 'gunpowder'),
  ('cannon', 'Cannon', 'siege', 'renaissance', 240, '[{"resourceKey":"iron","qty":40},{"resourceKey":"saltpeter","qty":15}]'::jsonb, 5, '{"combat":30,"movement":1,"defense":4}'::jsonb, 'gunpowder'),
  ('caravel', 'Caravel', 'naval', 'renaissance', 180, '[{"resourceKey":"wood","qty":60}]'::jsonb, 4, '{"combat":20,"movement":5,"defense":6}'::jsonb, 'navigation'),
  ('ironclad', 'Ironclad', 'naval', 'industrial', 400, '[{"resourceKey":"iron","qty":60},{"resourceKey":"coal","qty":40}]'::jsonb, 8, '{"combat":40,"movement":3,"defense":16}'::jsonb, 'steam_power'),
  ('rifleman', 'Rifleman', 'military', 'industrial', 260, '[{"resourceKey":"iron","qty":30},{"resourceKey":"saltpeter","qty":10}]'::jsonb, 5, '{"combat":45,"movement":1,"defense":10}'::jsonb, 'steel_making'),
  ('machine_gun', 'Machine Gunner', 'military', 'modern', 350, '[{"resourceKey":"iron","qty":40},{"resourceKey":"petrochemicals","qty":10}]'::jsonb, 6, '{"combat":60,"movement":1,"defense":12}'::jsonb, 'electronics'),
  ('submarine', 'Submarine', 'naval', 'modern', 600, '[{"resourceKey":"steel","qty":60},{"resourceKey":"uranium","qty":20}]'::jsonb, 10, '{"combat":70,"movement":4,"defense":20}'::jsonb, 'nuclear_fission'),
  ('rocket', 'Rocket', 'naval', 'modern', 800, '[{"resourceKey":"steel","qty":80},{"resourceKey":"electronics","qty":30}]'::jsonb, 12, '{"combat":90,"movement":6,"defense":12}'::jsonb, 'rocketry') on conflict (key) do nothing;

insert into public.recipes (key, name, output_resource_key, output_qty, inputs, building_key, unlock_tech_key) values
  ('smelting', 'Smelting', 'copper', 1, '[{"resourceKey":"copper-ore","qty":2}]'::jsonb, 'smithy', 'mining'),
  ('bronze_casting', 'Bronze Casting', 'bronze', 1, '[{"resourceKey":"copper","qty":2},{"resourceKey":"tin","qty":1}]'::jsonb, 'smithy', 'bronze_working'),
  ('iron_smelting', 'Iron Smelting', 'iron', 1, '[{"resourceKey":"iron-ore","qty":2},{"resourceKey":"coal","qty":1}]'::jsonb, 'smithy', 'iron_working'),
  ('steelmaking', 'Steel Making', 'steel', 1, '[{"resourceKey":"iron","qty":2},{"resourceKey":"coal","qty":1}]'::jsonb, 'foundry', 'steel_making'),
  ('electrolysis', 'Aluminum Refining', 'aluminum', 1, '[{"resourceKey":"bauxite","qty":2}]'::jsonb, 'power_plant', 'electricity'),
  ('milling', 'Milling', 'flour', 2, '[{"resourceKey":"wheat","qty":2}]'::jsonb, 'granary', 'agriculture'),
  ('baking', 'Baking', 'bread', 3, '[{"resourceKey":"flour","qty":2}]'::jsonb, 'granary', 'agriculture'),
  ('weaving', 'Weaving', 'cloth', 1, '[{"resourceKey":"cotton","qty":2},{"resourceKey":"flax","qty":1}]'::jsonb, 'workshop', 'guilds'),
  ('linenmaking', 'Linen Making', 'linen', 1, '[{"resourceKey":"flax","qty":2}]'::jsonb, 'workshop', 'guilds'),
  ('dyeing', 'Dyeing', 'red-dye', 1, '[{"resourceKey":"cochineal","qty":2}]'::jsonb, 'workshop', null),
  ('dyesynthesis', 'Synthetic Dye Production', 'blue-dye', 1, '[{"resourceKey":"indigo","qty":2},{"resourceKey":"chemicals","qty":1}]'::jsonb, 'laboratory', 'chemistry'),
  ('tannery', 'Tannery', 'leather', 1, '[{"resourceKey":"cowhide","qty":2}]'::jsonb, 'workshop', 'animal_husbandry'),
  ('dairy', 'Dairy', 'cheese', 2, '[{"resourceKey":"milk","qty":3}]'::jsonb, 'farm', 'animal_husbandry'),
  ('chocolatemaking', 'Chocolate Making', 'chocolate', 2, '[{"resourceKey":"cocoa","qty":2},{"resourceKey":"sugar","qty":1}]'::jsonb, 'workshop', 'preservation'),
  ('papermaking', 'Papermaking', 'paper', 1, '[{"resourceKey":"pulp","qty":2}]'::jsonb, 'workshop', 'writing'),
  ('cementmaking', 'Cement Production', 'cement', 1, '[{"resourceKey":"limestone","qty":2},{"resourceKey":"clay","qty":1}]'::jsonb, 'quarry', 'construction'),
  ('concretemaking', 'Concrete Production', 'concrete', 1, '[{"resourceKey":"cement","qty":1},{"resourceKey":"gravel","qty":1},{"resourceKey":"sand","qty":1}]'::jsonb, 'quarry', 'construction'),
  ('glassmaking', 'Glassblowing', 'glass', 1, '[{"resourceKey":"sand","qty":2}]'::jsonb, 'glassworks', 'glassblowing'),
  ('fertilizermaking', 'Fertilizer Production', 'fertilizer', 1, '[{"resourceKey":"potash","qty":1},{"resourceKey":"phosphate-rock","qty":1}]'::jsonb, 'laboratory', 'chemistry'),
  ('chemical_synthesis', 'Chemical Synthesis', 'chemicals', 1, '[{"resourceKey":"sulfur","qty":1},{"resourceKey":"potash","qty":1}]'::jsonb, 'laboratory', 'chemistry'),
  ('gunpowder_recipe', 'Gunpowder Manufacture', 'explosives', 2, '[{"resourceKey":"sulfur","qty":1},{"resourceKey":"saltpeter","qty":2},{"resourceKey":"charcoal","qty":1}]'::jsonb, 'arsenal', 'gunpowder'),
  ('refining_gasoline', 'Refine Gasoline', 'gasoline', 3, '[{"resourceKey":"oil","qty":2}]'::jsonb, 'refinery', 'petroleum_refining'),
  ('refining_diesel', 'Refine Diesel', 'diesel', 2, '[{"resourceKey":"oil","qty":2}]'::jsonb, 'refinery', 'petroleum_refining'),
  ('refining_kerosene', 'Refine Kerosene', 'kerosene', 2, '[{"resourceKey":"oil","qty":2}]'::jsonb, 'refinery', 'petroleum_refining'),
  ('refining_plastics', 'Plastics', 'plastics', 1, '[{"resourceKey":"naphtha","qty":2},{"resourceKey":"chemicals","qty":1}]'::jsonb, 'refinery', 'petroleum_refining'),
  ('refining_petrochemicals', 'Petrochemicals', 'petrochemicals', 2, '[{"resourceKey":"oil","qty":2}]'::jsonb, 'refinery', 'petroleum_refining'),
  ('semiconductormaking', 'Semiconductor Fabrication', 'semiconductors', 1, '[{"resourceKey":"silicon","qty":2}]'::jsonb, 'laboratory', 'semiconductors'),
  ('microchipmaking', 'Microchip Fabrication', 'microchips', 1, '[{"resourceKey":"semiconductors","qty":1},{"resourceKey":"gold","qty":1}]'::jsonb, 'laboratory', 'semiconductors'),
  ('batterymaking', 'Battery Assembly', 'batteries', 1, '[{"resourceKey":"lithium","qty":1},{"resourceKey":"cobalt","qty":1},{"resourceKey":"graphite","qty":1}]'::jsonb, 'factory', 'electricity'),
  ('enrichment', 'Nuclear Enrichment', 'uranium', 1, '[{"resourceKey":"uranium-ore","qty":3}]'::jsonb, 'power_plant', 'nuclear_fission'),
  ('nanofabrication', 'Nanofabrication', 'graphene', 1, '[{"resourceKey":"carbon","qty":2}]'::jsonb, 'nanofab', 'nanotechnology'),
  ('magnetmaking', 'Superconductor Magnets', 'magnets', 1, '[{"resourceKey":"rare-earth-elements","qty":2},{"resourceKey":"superconductors","qty":1}]'::jsonb, 'nanofab', 'superconductors'),
  ('fishing', 'Fishing', 'fish', 3, '[]'::jsonb, 'harbor', 'sailing'),
  ('minting', 'Minting', 'gold', 1, '[{"resourceKey":"gold-ore","qty":2}]'::jsonb, 'smithy', 'currency') on conflict (key) do nothing;
